- README.md
- package-lock.json
- package.json
- src/classes/Commands.ts
- src/classes/DiscordWebhook.ts
- src/classes/MyHandler.ts
- src/classes/Pricelist.ts
- src/lib/ptf-api.ts
**added**
- `!sales` command - Gets a list of listings that have been removed (removed, is like it means that item has been sold with that price, but it is not so accurate since more and more bot owner now auto-restart their bot(s)). (6c89635)
**fixed**
- bot crashed when `CUSTOM_PLAYING_GAME_NAME` does not exist in your ecosystem.json file. (56a143d)
- bot crashed when using `!block <steamID>` and `!unblock <steamID>`, if the owner forgot to put targeted `<steamID>` in it. (d644875)
- weird review offer messages when using Steam Chat.
**changed**
- For auto-accept INVALID_ITEMS/OVERSTOCKED, it is now only accepted if overpaid (equal value or not same will be sent for a review).
> Minor update

- README.md
- src/classes/Commands.ts
- src/classes/MyHandler.ts
- update `!adjustrate` command to also refresh Autokeys settings/price (scrap adjustment included) (12071d2)
- add `!relist` command - you need to wait for the first 30 minutes after your bot is up and you'll be able to run this command when you think there's some missing listings on backpack.tf. After you've executed this command, then you'll need to wait another 30 minutes before you can run it again (eff4c58)
> update !adjustrate command and add !relist command

- src/classes/DiscordWebhook.ts
- src/classes/MyHandler.ts
- fix bot crash when backpack.tf or Steam down (24cf715)
- some changes (23c5d3d, f21ef28)
> fix bot crash when backpack.tf or Steam down

- src/classes/MyHandler.ts
Change message/reason of 'The offer has been active for a while' to 'The offer has been active for a while. If the offer was just created, this is likely an issue on Steam's end. Please try again later'.
This message is sent when Steam trading is down, so it's important to also note that this is a very likely scenario rather than the trade being active for too long. This will clear up confusion/frustration when a customer receives this message within seconds of making the trade.
> change 'offer expired' message

- src/classes/DiscordWebhook.ts
- src/classes/MyHandler.ts
- add "steamrep.com", not just "backpack.tf down" when bot failed to check for banned status.
> a very minor update

- src/classes/Commands.ts
-Fixed the steamID in the url for steamProfile, backpackTF and steamREP (this problem is only when using !trade command, it show admin steamID instead of trade partner steamID).
-Added some improvements in messages for !trade & !trades commands.
> fix steamID url, improve !trades & !trade messages

- src/classes/MyHandler.ts
- src/lib/bans.ts
**Fix**
- the `Array.some()` method when checking whether Noise Maker exists in the pricelist or not. Previously it checks the entire Noise Maker sku instead of the only sku that is/are being checked. (7a4b8c5)
**Changes**
- add missing boolean (stricter type) when checking if trade partner is marked as scammer based on backpack.tf API. The bot will always check if trade partner is a scammer based on Steamrep.com, but if and only if something is wrong with Steamrep, then it will refer to backpack.tf API. (6fb563b)
> v1.6.2 - minor fix/changes

- src/classes/Commands.ts
- src/classes/MyHandler.ts
This commit fixes a typo in the "Trade should be finalized shortly" message, as well as updates other messages sent to users. This change is very small, and most likely does not warrant its own version change
> Message typo correction

- src/classes/MyHandler.ts
These code changes clean up the current `!uptime` logic.
Below are some example outputs from these code changes:
**Bot has been up for ~10 seconds:** `"Bot has been up for a few seconds."`
**Bot has been up for 3 minutes:** `"Bot has been up for 3 minutes."`
**Bot has been up for exactly 24 hours:** `"Bot has been up for a day (24 hours)."`
**Bot has been up for exactly 30 hours:** `"Bot has been up for a day (30 hours)."`
**Bot has been up for exactly 48 hours:** `"Bot has been up for 2 days."`
**Bot has been up for 2 weeks:** `"Bot has been up for 14 days."`
**Bot has been up for 4 weeks:** `"Bot has been up for a month (28 days)."`
> MyHandler: Uptime logic cleanup

- src/classes/Autokeys.ts
- src/classes/Commands.ts
- src/classes/Pricelist.ts
Since v1.7.0 update, if `ENABLE_AUTOKEYS` and `DISABLE_SCRAP_ADJUSTMENT` are set to `true`, the key rate will add `SCRAP_ADJUSTMENT_VALUE` value on every trade made.
> Autokeys - Scrap Adjustment investigation and solution

- package-lock.json
- package.json
- src/classes/Commands/utils.ts
This enhancement addresses #154 
**Note: Current implementation will find the nearest item by a distance of 3. This means that anything that is within 3 modifications of an item on the price-list will be found. This can be increased or decreased if it is shown to be too granular or not granular  enough.**
Below is an example of some example output from the current implementation of this feature:
> Add item name matching on buy/sell, Add js-levenshtein library

- src/classes/Commands/optionsCommands.ts
- fix `!config` command crashed the bot when trying to change anything in `discordWebhook` object that's other than `tradeSummary` sub-object.
> v2.0.1 - fixes

- src/classes/Commands/optionsCommands.ts
- src/classes/Listings.ts
This will give the user feedback for in case autorelist never got enabled when they configured autobump.
If the user is premium and enabled autobump it just silently fails because autorelist is set to false by default.
> Better autobump feedback

- src/classes/Commands/Commands.ts
- src/lib/tools/time.ts
This PR also includes thresholds for DayJS times. No longer will we have to deal with `44 seconds = 1 minute`!
> 🔁 update time taken to have numeric precision

- src/classes/Autokeys/Autokeys.ts
It's causing bot to loop into buying & selling for the same price when scrapAdjustment is enabled.
+ may cause to stay on low or too many keys for long time.
> don't add additional "1" to the min/max

- src/classes/MyHandler/MyHandler.ts
Example of the new startup summary: 
```2020-12-14 00:39:43 info: TF2Autobot v2.2.5 is ready | 1 item in pricelist | Listings cap: 70 | Startup time: 6s```
> Add startup time to "onReady" summary

- src/classes/MyHandler/MyHandler.ts
- 🐛 fix false INVALID_ITEMS overpay
- If `manualReview.invalidItems.givePrice` is `false` and `manualReview.invalidItems.acceptOverpay` is `true`, then if someone takes anything on our side that is not priced and their side has some value, the bot will accept the trade.
- Now the trade will be held for review.
> v2.3.4 - patch

- src/classes/Pricelist.ts
Fixes bot crashing if you ran a remove on a genric sku like `!remove sku=31112;5`
> 🐛 getIndexWithGenerics crashing if sku is already generic

- src/classes/Pricelist.ts
The previous fix effectively disabled generic matches. This fixes the fix. 🥇 
always enter "generic" code if sku qualifies
  - process sku in generic code branch if sku qualifies
  - return -1 on non-qualified skus
  - added comments to make code intent clearer
> 🐛  always enter "generic" code if sku qualifies

- src/classes/Commands/functions/manager.ts
- src/classes/InventoryManager.ts
- src/classes/MyHandler/MyHandler.ts
Based on my observation, some items are still missing and the bot said in the log that "❌ Nothing to refresh". I have to manually update to disable then re-enable it so the item will be listed to sell.
This commit might fix this issue.
Please review it.
Thank you.
> 🔨 improve auto-check missing listings

- src/classes/Commands/functions/pricelistManager.ts
Allows for always displaying a pricelist entry's group, even if that group is `all`.
Did some light testing (as the changes are minimal) which can be seen below.
> Group "all" updates

- src/classes/Carts/Cart.ts
- src/classes/Carts/UserCart.ts
- Prevent the bot from picking up weapons that are in the bot pricelist with your `miscSettings.weaponsAsCurrency.enable` is set to `true`, when the trade partner uses commands (`!buy`/`!sell`/`!buycart`/`!sellcart`).
> 🐛 patch: `weaponsAsCurrency` using command

- src/classes/Commands/sub-classes/Review.ts
- 🔨 check to exist with timestamps instead of received
> small fix to `!offerinfo` command

- src/classes/Options.ts
Self-explanatory. This change is done to account for variations in the `🎗️` emoji color across devices (see: (https://emojipedia.org/reminder-ribbon/)
> refactor: 💡 change hot rod sheen emoji to cherry blossom

- src/classes/Carts/UserCart.ts
- Only pick weapons if needed (of course only if your `miscSettings.weaponsAsCurrency.enable` is set to `true`).
- closes #341
- buying item with 0.05 ref price
- buying item with no 0.05 ref
> 🏹 Update on how the bot should pick weapons when constructing an offer

- .github/workflows/docker-commit.yml
- .github/workflows/docker-latest-tag.yml
- .github/workflows/docker-release.tag.yml
I quickly realized that 15.10 should not be used since it's not LTS and `lts-alpine` is LTS. I decided to change the Docker images build for LTS only.
> [fix] Build images only for Node.js LTS

- README.md
I have added a `docker build` badge for the `Docker` CI workflow. Might add more later in the process after v3.5.0.
> [readme] Docker badge

- src/classes/Commands/sub-classes/PricelistManager.ts
-    Problem:
- only show 100 entries if too many.
- show in `/code` and entry form will cause the chat window to lag
-    Screenshot:
-    Only show `sku - name`
-    Can list all and no lagging issue.
.
.
.
> 🔨 refactor `!find` command

- src/classes/Carts/UserCart.ts
- src/classes/Inventory.ts
- src/classes/Listings.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/Options.ts
- src/lib/tools/getHighValue.ts
- src/schemas/options-json/options.ts
- src/types/modules/@tf2autobot/tradeoffer-manager/index.d.ts
Previously, all spelled items were considered high-value. adding this option on request.
> ✨ option to select highValue spells

- src/app.ts
Both SIGINT and SIGTERM manifest the same way (almost the same way; SIGKILL cannot be caught, tho), so I assume it can be caught too. Many OSes send `SIGINT` and after a certain period of time (depending on the executor) sends SIGTERM, then SIGKILL to kill the process.
It would be nice to have `SIGTERM` too because it helps on any OS to handle crashes like this.
> [3.x] Exclude SIGTERM from crash handle

- src/classes/Pricelist.ts
- fixes:
- Occurred because the socket is running before we get the globalKeyPrices
> ⛔ don't execute if globalKeyPrices still undefined

- src/classes/Pricelist.ts
update on partial price feature:
- partially price an item if newSelling - currentBuying < 0 OR item group is "isPartialPriced".
> 💱 partial price on `isPartialPriced` group

- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Options.ts
- src/lib/DiscordWebhook/sendAlert.ts
- src/schemas/options-json/options.ts
If the bot accepts an Unusual item that is not on the price list it will not put it back up for sale unless autoAddInvalidUnusual is set to true. The option is set to false by default to protect users who use the generic price SKU and unaware that autoAddInvalidItems would sell off anything purchased via that generic sku.
Based off conversation in #400
> Add option toggle autoAddInvalidUnusual = false

- src/lib/tools/summarizeOffer.ts
- 🤐 Compress summary only if too many (will be able to show more items - Discord Webhook only)
- 🎨 Stock changes now will be shown in the offer review summary (only if `tradeSummary.showStockChanges` is set to `true`)
> 🎨 Changes to trade summary

- src/classes/Trades.ts
- On failed action (accept/decline):
- Ignore sending a notification to admin/Discord Webhook if the `eresult` error is "AlreadyRedeemed" or "InvalidState", and if the error message includes "is not active, so it may not be accepted", but the bot will still retry to accept after 30 seconds in the background.
- On failed to error while trying to accept mobile confirmation:
- Ignore sending a notification to admin/Discord Webhook and do not perform auto-retry if the error message includes "Could not act on confirmation" or "Could not find confirmation for object"
> 🔕 ignore some error on fail action or to accept

- src/classes/Carts/UserCart.ts
- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Inventory.ts
- src/classes/Listings.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/Trades.ts
- src/lib/data.ts
- src/lib/tools/summarizeOffer.ts
> 🔨 refactor: use Map and Set

- src/lib/tools/summarizeOffer.ts
- Stock changes (only if you have `tradeSummary.showStockChanges` set to `true`)
- 🔨 fix a negative value on their side (offer review and logs) - @idinium96
> patch - v3.6.2

- src/classes/Commands/sub-classes/Manager.ts
- src/classes/MyHandler/MyHandler.ts
Prevent this chaos when `miscSettings.crateListings.enable` is set to `false`:
https://gyazo.com/1e45574ad9246a861f47ffe13bdee0dd
> ⛔ do not execute auto-check if `createListings` is disabled

- src/classes/Commands/sub-classes/Message.ts
- src/classes/Commands/sub-classes/Review.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
Option to hide owner's nickname on `!message` & `!accept`/`!decline`(if reply is included) commands.
Default is true (show nickname).
> ✨ add an option to not show owner's nickname

- src/classes/MyHandler/MyHandler.ts
- src/classes/Options.ts
- src/classes/Pricelist.ts
- src/lib/DiscordWebhook/sendAlert.ts
- src/schemas/options-json/options.ts
Mostly for custom pricer user, but can also occur if you manually change the `autoprice` property of any item that does not exist in the pricer pricelist, i.e. most skins or some unusual that does not exist in the source pricelist should be manually priced, and then if you edit your `pricelist.json` and change the `autoprice` to `true` (or even if you use `!update all=true&autoprice=true` command), an error will occur here:
https://github.com/TF2Autobot/tf2autobot/blob/43ba1e54c67b444d376b436f034877545191fa53/src/classes/Pricelist.ts#L770
and then your bot will use the temporary "hard-coded" key prices:
https://github.com/TF2Autobot/tf2autobot/blob/43ba1e54c67b444d376b436f034877545191fa53/src/classes/Pricelist.ts#L643-L648
These changes will skip the affected item and temporarily disabled …
> 🚧 add failsafe on updateOldPrices method

- src/classes/Commands/sub-classes/PricelistManager.ts
- src/classes/Pricelist.ts
> 🐛 fix manual pricing reverted to autoprice

- src/classes/Pricelist.ts
Fix bot does not apply PPU when this occurs:
- The bot bought for 16 keys (which is about ~7552 in scrap value at 52.44 ref/key):
- And then the price got updated with 14 keys, 21 ref / 15 keys, 52.44 ref - Which is for the selling price is basically the same as the previous buying price (broken prices.tf 😭).
And thus the item was sold for 0 profit.
> PPU: 🔨 fix the unintended rare occurrence

- src/classes/MyHandler/offer/accepted/updateListings.ts
This can occur if your `pricelist.autoRemoveIntentSell.enable` is set to `true`, and also the `autokeys.enable` set to true and Autokeys was active selling and after a trade, the stock for keys goes to 0, which triggered the `autoRemoveIntentSell` first before the disable Autokeys method.
> 🐛 fix false Autokeys failed to disable error

- src/classes/Pricelist.ts
Doing this:
```ts
return this.prices.findIndex(entry => entry.sku === (sku ? sku : SKU.fromObject(parsedSku)));
```
will make it to poorly perform the task -
But this:
```ts
sku = sku ? sku : SKU.fromObject(parsedSku);
const findIndex = this.prices.findIndex(entry => entry.sku === sku);
return findIndex;
```
Surprising fast -
This "without delay" thing is just the debugging thing I added here:
https://github.com/TF2Autobot/tf2autobot/blob/b059c6273e849159f65912204bef9ff5631e1060/src/classes/Listings.ts#L399-L425
> 🐛 fix performance issue on start (with huge listings/pricelist)

- src/classes/Commands/sub-classes/PricelistManager.ts
- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Pricelist.ts
- src/schemas/pricelist-json/pricelist-add.ts
- src/schemas/pricelist-json/pricelist.ts
- any existing "isPartialPriced" group will be reset to "all" and `isPartialPriced` will be set to `true` (will be set to `false` if the group is not "isPartialPriced") when updating the bot to the latest version.
> ✨ add new "isPartialPriced" key in pricelist entry

- src/classes/Commands/sub-classes/Request.ts
because Mann Co. Supply Crate Key is excluded.
> 🔨 fix wrong info on `!pricecheckall` cmd

- src/classes/MyHandler/MyHandler.ts
- Only if that particular item is priced. If no price found with the pricer, then it will still show a negative profit.
> 🐛 possible fix negative profit when accepting invalid items

- src/classes/Pricelist.ts
- ✅ catch error on `updateOldPrices` method so it will not get caught on `setupPricelist` method (which will result in using temporary key prices).
> 🦾 catch error like a boss

- src/classes/Carts/UserCart.ts
- src/classes/Handler.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/accepted/processAccepted.ts
- src/classes/Options.ts
- src/classes/Trades.ts
- src/lib/DiscordWebhook/sendTradeSummary.ts
- src/lib/tools/time.ts
- src/schemas/options-json/options.ts
- src/types/modules/@tf2autobot/tradeoffer-manager/index.d.ts
- Show time taken to construct offer (if trade partner use chat) or to process offer (if trade partner sent an offer to the bot) in the trade summary "Time taken".
- New option: `tradeSummary.showDetailedTimeTaken` (default is `true`).
> ✨ opt to show detailed time taken

- src/classes/Commands/sub-classes/PricelistManager.ts
"bank", "sell", or "buy" instead of 2, 1, or 0 on `!getAll` and `!find` commands.
> 🔄 translate intent in number to string

- src/classes/Bot.ts
- src/classes/Inventory.ts
- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
Legacy Painted item does not have a description on them, thus we use image URL to detect if the item is Team Spirit painted. Legacy Paint is Team Spirit will missing blue color attribute.
Example of an item with Legacy Paint:
Regular Team Spirit:
> ✨ detect item with Legacy Paint

- src/classes/Commands/sub-classes/Review.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/accepted/processAccepted.ts
- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/MyHandler/offer/review/reasons/invalidItems.ts
- src/classes/Options.ts
- src/lib/extend/item/getSKU.ts
- src/lib/tools/export.ts
- src/lib/tools/getHighValue.ts
- src/lib/tools/summarizeItems.ts
- src/lib/tools/summarizeOffer.ts
- src/lib/tools/testSKU.ts
- src/schemas/options-json/options.ts
- Trading Card, CS:GO items, etc (Discord Webhook: hyperlink not enabled).
- Cannot add to the pricelist.
- All offers that contain non-TF2 items will always be held for review under 🟨_INVALID_ITEMS (manually accept/decline it).
- Might cause -ve profit (on `!stats` or `!statsdw` commands) when accepted.
- New options.json property:
- `offerReceived.alwaysDeclineNonTF2Items` (default is `true`)
- Steam Chat:
- Discord Webhook:
-- with `showStockChanges` enabled:
> ✨ support processing Non-TF2 items (offer only)

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Misc.ts
- src/classes/Commands/sub-classes/PricelistManager.ts
- src/classes/Inventory.ts
- src/classes/InventoryManager.ts
- src/classes/Listings.ts
- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Options.ts
- src/classes/Pricelist.ts
- src/lib/tools/summarizeOffer.ts
- src/schemas/options-json/options.ts
- Currently, if you set `normalize.festivized.our` to `false` and `normalize.festivized.their` to `true`:
- Let say you have a buy order for "Australium Rocket Launcher".
- When the bot receives an item, let say "Festivized Australium Rocket Launcher", it's first recognized as "Australium Rocket Launcher" (it's normalized since `normalize.festivized.their` is set to `true`).
- Then once the item is in the bot inventory, it's now recognized as "Festivized Australium Rocket Launcher", and thus the `amountCanBuy` is still not 0 and the buy order is still up.
- This implementation will also take into account the Non-Normalized variants.
- Before (or set to `false`)
- After (set to `true`, No buy order created)
- Before (or set to `false`): https://gyazo.com/1a4951b96b50c77c2d9d27afef1e1414
- …
> ✨ opt for amount to include non-normalized items

- src/classes/Inventory.ts
> 🐛 fix Team Spirit paint detected as Legacy Paint

- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Listings.ts
- src/classes/MyHandler/MyHandler.ts
replace `amountCanSell` with only looking for the amount of an item, with `includeNonNormalize` set to `false`.
> 🔨 fix repetitive false missing listings

- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/Options.ts
- src/lib/DiscordWebhook/sendTradeDeclined.ts
- src/schemas/options-json/options.ts
adds ability to receive declined trade summaries.
Sends Discord Webhook message or Steam message on declined offers.
Uses webhook `trade-declined`.
Message includes the reason and the description about why the trade was declined.
Adds new option to `options.json` called tradeDeclined
Fixes: https://github.com/TF2Autobot/tf2autobot/issues/582
> Add Trade Declined Summary

- src/classes/Commands/functions/utils.ts
- src/lib/items.ts
Looks the same, but different defindex:
- If you already added the one with 5737, then you'll not be able to add 5738.
> 🔨 standardize defindex for Mann Co. Stockpile Crate

- src/schemas/options-json/options.ts
Fix no errors thrown when the `autokeys` is just set to `"autokeys": true` in options.json file (also for some others that were missing the type).
It should always be an `object` type.
> 🔨 fix missing `type: 'object'` in options.json schema

- src/classes/MyHandler/offer/accepted/processAccepted.ts
- 🐛 fix missing `trade` type in `messageAdmins` (d78920a)
- setting `"none"` in the `ALERTS` array in the `ecosystem.json` or `.env` files should stop the bot from sending the accepted trade summaries to all admins.
> prepare v4.1.5

- src/classes/Options.ts
- src/classes/__tests__/Options.ts
If a user has a subset of options.json the assumption of keys being present in replaceOldProperties can cause crashes.
> fix migration crashing with limited options.json

- src/classes/MyHandler/MyHandler.ts
If your `miscSettings.checkUses.duel` or `miscSettings.checkUses.noiseMaker` is set to `true`, then if your bot has any of it that is not full use (5x uses or 25x uses), the bot will decline the trade, even though it's on your bot side.
So this should fix it.
> 🐛 fix unable to sell not-full uses items

- .example/options.json
- src/classes/MyHandler/MyHandler.ts
- 🐛 fix `discordWebhook.ownerID` (again) (#759) - already merged to master by accident
- 🐛 fix unable to sell non-full uses items (#760)
> prepare v4.2.6

- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/MyHandler/offer/review/send-review.ts
- src/classes/Options.ts
- src/lib/DiscordWebhook/sendTradeDeclined.ts
- src/schemas/options-json/options.ts
> 💡 refactor handling offer review

- src/classes/MyHandler/MyHandler.ts
The item exists, but the bot failed to detect it. This should fix it (only on offer received - might still problematic when the trade partner try to use the command to buy stuff from the bot)
> 🐛 fix false understocked

- src/classes/Commands/sub-classes/Misc.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
might be useful for those that banks craft/uncraft weapons (higher value weapons not included).
set the value to `false` to show all (amount will be zero if not exist - obviously).
> ✨ option to show all craft/uncraft weapons

- src/classes/MyHandler/MyHandler.ts
A bug that leads to an exploit was introduced on v4.4.0/v4.4.1, where if your bot has any item in the pricelist with:
- an `intent` set to `buy`
- the selling price set to `0` (by default if you set the intent to `buy` and only set the buying price, this will be `0`)
**The bot will accept the trade even if their side is empty.**
Setting intent to `bank` with selling price set to `0` is not possible - except if you manually edit the pricelist.json file, so should not be worry if all your items are set to `bank` with the non-zero selling price.
My test:
> URGENT - 🐛 fix an exploit introduced on v4.4.0/v4.4.1 update

- .example/options.json
- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/notify/declined.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
Because it's still exploitable if they sent any valued _free_ item(s) (the bot think it's overpaid):
> ⛔ always decline an offer with zero selling price (our side)

- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/notify/declined.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
- The trade partner is trying to buy (to take) items (our items) with the intent set to buy? Declined (they should sell to us, not buy from us).
- The trade partner is trying to sell (to give) items (their items) with the intent set to sell? Declined (they should buy from us, not sell to us).
- This update will also automatically remove the previously added `customMessage.decline.takingItemsWithZeroSellingPrice` property.
> Just decline an offer containing items with wrong intent

- src/lib/extend/item/getSKU.ts
The wrong detection causing the bot to think it does not exist or makes the offer put to review:
> 🐛 fix unable to detect Collector's Chemistry Set

- src/classes/Bot.ts
- src/types/modules/steam-user/index.d.ts
- src/types/modules/steamcommunity/index.d.ts
Add a listener for the `newItems` event on our `SteamUser` instance. If the number of new items is not zero, the listener `SteamCommunity.resetItemNotifications()` to load our inventory page and reset our item notifications to zero.
Fixes: #871
> Add resetting item notifications

- src/app.ts
- src/classes/BotManager.ts
Closes #573
So this is an old issue: bots cannot be restarted via steam command/message if it runs in docker with PM2.
If my logic is not flawed, this should fix the issues by checking if there is a `DOCKER` variable and just terminate the process while doing its cleanup.
The only caveat here is that when running the container, it should contain `--restart=always` and `-e DOCKER=1`
```bash
$ docker run \
-v $(pwd)/tf2autobot_data/123456:/app/files/123456 \
-v $(pwd)/tf2autobot_data/ecosystem.json:/app/ecosystem.json \
--restart=always \
-e DOCKER=1 \
tf2autobot/tf2autobot:latest-14.16.0-alpine
```
The change is reverse compatible due to the `DOCKER` variable check.
> [fix] Force stop when docker run is enabled

- src/classes/Bot.ts
- src/classes/Commands/Commands.ts
- template.ecosystem.json
- template.env
😂
Note:
- This will only affect requests that the bot will send to the backpack.tf through [@TF2Autobot/bptf-listings](https://github.com/TF2Autobot/node-bptf-listings) only. All other web/API requests outside that module will still send the bot version.
- The default is "TF2Autobot - Run your own bot for free" (credit: @Nicklason), and if you fill in the `USERAGENT_HEADER_CUSTOM` value, it will be "TF2Autobot - \<Whatever you put it there\>".
- I don't know if there's any character limit, but **please use it wisely, and at your own risk!**
> Custom user agent header

- src/classes/Listings.ts
Instead of calling `getDetails` twice, we just use `replace`.
I want to use `replaceAll` by upgrading the compiler target to ES2021, but this error appears:
It's nothing, but might always make the Docker automatic push, etc, to fail.
> Fixing issue #1095

- src/classes/Bot.ts
- src/classes/BotManager.ts
- src/classes/IPricer.ts
- src/classes/Pricelist.ts
- src/lib/pricer/custom/custom-pricer.ts
- src/lib/pricer/pricestf/prices-tf-pricer.ts
Credit @EliteOneTube:
The error in question which crashes the bot was: `WebSocket was closed before the connection was established`, which should be fixed on the 1f66f50 commit.
Before this commit, the bot still initialize the `socketManager`, and added the `error` eventListener, which then if `enableSocket` is set to `false`, the `shutDown` is called, but `ws` don't have `removeAllEventListener` method, so that the `error` event never get deleted, thus when `error` event is emitted, the bot tries to reconnect while the websocket is in the `CONNECTING` state which results in crashing the bot despite having the enableSocket option disabled.
> 🐛 fix ENABLE_SOCKET not properly done its job

- src/lib/extend/item/getSKU.ts
Will now throw an error if `market_hash_name` is falsy.
> Fix crash on getting SKU from EconItem

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Help.ts
- src/lib/bans.ts
**[Exclusive Marketplace.tf Sellers]**
Withdraw items that does not exist in your Marketplace.tf Dashboard items.
Parameter:
- `max` (optional): default is 1. If the amount of item x in your Marketplace.tf dashboard + your bot inventory > max, then the item will remain untouched.
- `ignorepainted` (optional): default is `false`. If set to true, your bot will not send any painted items (only if your `normalize` and `highValue.painted` settings are correct).
- `withgroup` (optional): no default value. If you want to withdraw only a certain group in your pricelist, then use this.
Usage example:
- `!withdrawMptf` (max will be 1, ignorepainted will be false)
- `!withdrawMptf max=3`
- `!withdrawMptf ignorepainted=true`
- `!withdrawMptf max=2&ignorepainted=true`
- `!withdrawMptf withgroup=mptf` …
> ✨ `!withdrawMptf` command

- src/app.ts
- src/classes/Bot.ts
- src/classes/Carts/UserCart.ts
- src/classes/Commands/sub-classes/Help.ts
- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Commands/sub-classes/Message.ts
- src/classes/Commands/sub-classes/Review.ts
- src/classes/Handler.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/interfaces.ts
- src/resources/paths.ts
An option to add a reason why a user is blocked for future reference (will be shown in the `!blockedList` command).
Usage: `!block <steamid> [reason]`
Example: `!block 7659358192 Trying to exploit`
You can also add the reason for already blocked users with the same command.
Also, note that people that are automatically blocked (during friend requests, receiving an offer, or sending an offer) will be automatically added with `[onFriendRequest]`, `[onReceivedOffer]`, and `[onSendingOffer]`, respectively.
> ✨ Improvement on the `!block` command

- src/classes/MyHandler/offer/accepted/processAccepted.ts
- src/classes/MyHandler/offer/notify/declined.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/MyHandler/offer/review/process-review.ts
- src/classes/Trades.ts
- src/lib/DiscordWebhook/sendTradeDeclined.ts
- src/lib/DiscordWebhook/sendTradeSummary.ts
- src/lib/tools/valueDiff.ts
This should fix this kind of problem:
(note: this problem is likely to happen if you set the `miscSettings.showOnlyMetal.enable` to `false`).
> 🐛 fix wrong profit/loss from over/underpay info

- src/classes/Commands/sub-classes/Status.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/Trades.ts
- src/lib/DiscordWebhook/sendStats.ts
- src/lib/tools/polldata.ts
- src/lib/tools/profit.ts
- src/lib/tools/stats.ts
- src/resources/paths.ts
Rotate polldata every time the file size exceeds 5 MBs
Some possible QoL changes for the future:
- Add an option to the config to customize the maximum size of each polldata file
- Increasing the maximum size, while already having polldata files saved at a smaller size will cause the bot to start filling up the older, smaller sized files again, which means we will no longer be able to rely on modification date of the file to correctly sort our trades. All trades will have to be sorted in this case for the stats calculations, which will make it slower.
- Remove duplicate entries
- Active trades and recently processed trades at the time of switching to a new polldata file will appear in both the old and the new file.
- These duplicates are handled by using the most recent entry when loading …
> Rotate polldata

- package-lock.json
- package.json
- src/classes/Commands/Commands.ts
- src/classes/Commands/functions/utils.ts
- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Commands/sub-classes/PricelistManager.ts
- src/classes/Commands/sub-classes/Request.ts
- src/classes/Commands/sub-classes/Status.ts
- src/lib/extend/item/getSKU.ts
- src/lib/items.ts
Revoking changes made on #394, which means you will be able to add Strange Decorated Weapon (or Skins) that has two different Strange variants (one with quality Strange, and the other one with quality Decorated Weapon and elevated quality Strange).
The bot will no longer recognize the two variants as the same item.
Also:
Any sku with `;strange` (Elevated Strange Quality) on Decorated Weapons (or Skins) will now generate an item name with `(e)` (explicit) on it.
Example:
- `197;15;u703;w2;pk200;strange;kt-3`: Strange(e) Cool Professional Killstreak Bloom Buffed Wrench (Minimal Wear)
- `31024;5;u17;strange`: Strange Sunbeams Crack Pot
- `336;3;strange`: Strange Vintage Stockbroker's Scarf
- `878;1;strange`: Strange Genuine Foppish Physician
- `30498;13;strange`: Strange Haunted Hooded …
> 🧩 Make the bot recognize Strange Skins variants.

- package-lock.json
- package.json
- src/classes/Bot.ts
- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Trades.ts
Should help with `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` problem, which crashes the bot. This will also significantly help reduce memory usage.
From the latest changes made on [TF2Autobot/tradeoffer-manager](https://github.com/TF2Autobot/tradeoffer-manager), the bot will only cache trade history for only [up to 200 trades only](https://github.com/TF2Autobot/node-steam-tradeoffer-manager/commit/4f55e65c8e3865123d5c4eff99059d5fe53f232a), from the original 1100.
Some screenshots:
Before:
After:
Some bots can even go lower than that. It's based on the bot trades history.
> Reduce memory usage

- src/classes/Pricelist.ts
- src/lib/DiscordWebhook/pricelistUpdate.ts
Fix:
- Using raw item name:
- Might also fix calculation on the price differences 
Update:
- Style - make it looks the same as in the `#price-update-all` channel on the TF2Autobot Discord server.
> 🔄 update price update (discord wb), fix name

- src/classes/MyHandler/MyHandler.ts
- src/classes/Pricelist.ts
- src/classes/Trades.ts
- src/types/modules/@tf2autobot/tradeoffer-manager/index.d.ts
Credit: @ZeusJunior
Btw, I am not so sure how to continue this. Anyone that knows, feel free to contribute.
The idea is:
- If an offer was rolled back:
- update the existing assetid in pricelist to the new one.
> handle change of item assetid(s)

- src/lib/pricer/custom/custom-pricer-socket-manager.ts
Token will be sent when establishing a connection with the server instead of emiting an event for authentication. Removed the listener on the unauthorized event. If a client is not authorized the error will come through the event connect_error.
> Authenication with custom-pricer using middleware

- src/lib/tools/pure.ts
Fixes:
Will show `1 key, 0 ref` or `0 ref` instead of just `0`.
> 🎨 Fix pure stock

- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Options.ts
- src/lib/DiscordWebhook/sendAlert.ts
- src/schemas/options-json/options.ts
> ✨ an option to reset to autoprice once sold

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Manager.ts
- src/classes/Commands/sub-classes/Misc.ts
- src/classes/DiscordBot.ts
Fixes:
- Ghost "Got new message  from <Discord Bot Name>"
- Misalignment:
> 1147 extension

- src/lib/DiscordWebhook/pricelistUpdate.ts
- src/lib/DiscordWebhook/utils.ts
This issue was introduced on [v4.14.0](https://github.com/TF2Autobot/tf2autobot/releases/tag/v4.14.0) when upgrading the Discord Webhook requests to use Axios.
> 🔨 fix not handle Discord webhook price update rate limit

- src/classes/Inventory.ts
- src/classes/Options.ts
- src/lib/extend/item/getSKU.ts
- src/schemas/options-json/options.ts
- src/types/modules/@tf2autobot/tradeoffer-manager/index.d.ts
New options:
- `normalize.craftNumber.our` (default is `false`)
- `normalize.craftNumber.their` (default is `false`)
> 🔨 add missing craftNumber parsing

- src/classes/Trades.ts
Prevent never-ending "The request is a duplicate and the action has already occurred in the past, ignored this time" on fetching inventory when the bot received and processed a lot of offers in a short period.
> ✅ properly handle inventory fetch

- package-lock.json
- package.json
- src/classes/Bot.ts
- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Help.ts
- src/classes/Commands/sub-classes/Misc.ts
- src/classes/DiscordBot.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/Trades.ts
- src/lib/bans.ts
- ✨ Add `!links` command ([#1236](https://github.com/TF2Autobot/tf2autobot/pull/1236))
- ✅ Properly handle inventory fetch ([#1228](https://github.com/TF2Autobot/tf2autobot/pull/1228))
- ✅ Allow Discord bot to chat with non-admin ([#1234](https://github.com/TF2Autobot/tf2autobot/pull/1234), [a39cf2c](https://github.com/TF2Autobot/tf2autobot/pull/1233/commits/a39cf2cfb28fe93e2b154abd46ec64d13f2a5acf), [483dbbe](https://github.com/TF2Autobot/tf2autobot/pull/1233/commits/483dbbee85b50bbdbbec61e8ebdd4d1a0ad2067a))
- ✨ Add your bot to the TF2Autobot Discord server! Read: [wiki](https://github.com/TF2Autobot/tf2autobot/wiki/Setting-up-Discord-interface#add-your-discord-bot-to-the-tf2autobot-discord-server)
- 🛑 Throw an error if Rep.tf returns invalid response message …
> prepare v5.1.0

- src/classes/Bot.ts
- src/classes/DiscordBot.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
```json
// DO NOT INCLUDE COMMENTS (RED HIGHLIGHTS) IN YOUR OPTIONS.JSON FILE
"discordChat": {
"online": {
// Default: "Listening to incoming offers"
"type": "LISTENING", // LISTENING | PLAYING | COMPETING | WATCHING
"name": "incoming offers",
"status": "online" // online | idle | dnd | invisible
},
"halt": {
// Default: "Playing ? No, Halted ⛔"
"type": "PLAYING",
"name": "? No, Halted ⛔",
"status": "idle"
}
}
```
- It's impossible to create custom status. Idk why, probably just Discord.js.
- When online and ready:
- When put into halted mode (`!halt`):
> 🎨 Discord presence implementation

- src/classes/Pricelist.ts
Should fix this annoying problem:
> 🚮 remove unnecessary operation

- src/classes/Bot.ts
Make sure to not run the automatic check for missing/mismatching listings during halt mode, or else, this will run over and over:
> 🔨 Disable check for missing/mismatching listings during halt mode

- src/app.ts
Apparently, throwing an error inside Promise `.catch` block will cause a chaining effect.
This should resolves the issue with "Unhandled rejection...".
> Startup crash

- src/classes/Bot.ts
- src/classes/Options.ts
- src/lib/bans.ts
The problem with previous function based bans check is that, this
https://github.com/TF2Autobot/tf2autobot/blob/a3465225bd7973c502cc1b092e098246765f3bd8/src/lib/bans.ts#L7
and
https://github.com/TF2Autobot/tf2autobot/blob/a3465225bd7973c502cc1b092e098246765f3bd8/src/lib/bans.ts#L19
Might be conflicting when we're processing a lot of offer at the same time.
Doing it in class will make everything isolated, but I am not sure if this will cause a memory leak, or will be managed my GC itself.
> Check bans as class

- src/classes/Trades.ts
This bug was introduced in the [v5.1.0](https://github.com/TF2Autobot/tf2autobot/releases/tag/v5.1.0) ([#1228](https://github.com/TF2Autobot/tf2autobot/pull/1228)) update.
The bot will go "Online" and never play Team Fortress 2 again if the bot sends an offer, counter an offer, or countered offer is declined.
This should fix this issue.
> 🐛 Fix bot exit TF2 and never play again

- package-lock.json
- package.json
Previously, these weapons are not included in the craftable weapons (for crafting into scrap metals or tokens, not to trade):
- Dragon's Fury (1178)
- Thermal Thruster (1179)
- Gas Passer (1180)
- Hot Hand (1181)
- Second Banana (1190)
This should now be included.
> 🔨 Add Jungle Inferno weapons to the craft list

- src/app.ts
One time my bot got a Steam issue, it didn't crash properly (stuck) since the `catch` was removed to fix an issue with the `loginkey` thing.
Hopefully, this will solve it.
> 🔨 Fix still not properly crash on start if there's a problem

- src/classes/Commands/sub-classes/Manager.ts
- Add `--omit=dev` tag into `npm install` will help reduce the time taken to complete by ignoring any dev dependencies.
> 🔄 Update `!updaterepo` command

- src/classes/Commands/sub-classes/Request.ts
- 🔄 Make sure to filter `assetid` and painted sku as well, as it is not supported by prices.tf (will just throw error 500)
> 🔄 Update `!pricecheckall` command

- src/classes/Commands/sub-classes/Misc.ts
- src/classes/Listings.ts
- src/lib/tools/getAttachmentName.ts
- src/lib/tools/getHighValue.ts
- 🔨 Refactor duplicated `getAttachmentName` function ([53587eb](https://github.com/TF2Autobot/tf2autobot/commit/53587ebaf504431fbf6f58db871f12294e282fe8))
> 🔨 Refactor codes

- src/classes/Commands/sub-classes/PricelistManager.ts
- src/classes/Inventory.ts
- src/classes/MyHandler/MyHandler.ts
- src/lib/tools/getHighValue.ts
This ensures that high value items are entered into the getHighValue map with the appropriate price key
> 🐛 fix high value items not checking for asset id price

- package-lock.json
- package.json
- src/lib/pricer/pricestf/prices-tf-api.ts
Might fix the issue where the bot doesn't even bother to get new JWT from prices.tf. Quite ugly tbh.
> 🔨 Resolve prices.tf 401 issue

- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/utils/craftClassWeapons.ts
> 🐛 Fix unhandled rejection error that crashes the bot

- src/lib/tools/summarizeItems.ts
> 🐛 Show spot price instead of current price on the trade summary

- src/classes/Commands/sub-classes/Manager.ts
Fixes:
Even when your bot only has 1 friend (you, or anyone in the `KEEP` array), the bot still says removing some thousands of friends.
> 🐛 Fix bot removing non-friends (should not) on !clearfriends command

- src/classes/MyHandler/offer/accepted/updateListings.ts
Not just group, any custom listings note might also be reset to default.
Credit: Herrgard#0061
> 🐛 Fix group being altered on reset autoprice

- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
New options:
- `highValue.retainOldGroup` (default is `false`)
- `highValue.customGroup` (default is `highValue`)
If the `highValue.retainOldGroup` is set to `true`, when an item is put to hold because it contains some of the high-value attachments, the group will remain untouched.
> ✨ Add an option to retain old group on highValue hold

- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/accepted/processAccepted.ts
- src/classes/MyHandler/offer/notify/declined.ts
- src/classes/MyHandler/offer/processDeclined.ts
- src/classes/MyHandler/offer/review/process-review.ts
- src/classes/MyHandler/offer/review/send-review.ts
- src/classes/Trades.ts
- src/lib/DiscordWebhook/sendTradeDeclined.ts
- src/lib/DiscordWebhook/sendTradeSummary.ts
- src/lib/tools/valueDiff.ts
#1173 extension
- The core issue is in the [src/lib/tools/valueDiff.ts](https://github.com/TF2Autobot/tf2autobot/compare/development...1173-extension?expand=1#diff-dadd3c4d540560a008f3bf2b990b0bfec4e9d4c0bd70560c7b2f5851967747a7):
- Instead of getting the `keys` and `metal`, we just take the `total` value.
- Also use the spot key rate instead of the current key rate.
> 🐛 Fix profit/loss from over/underpay info on summary (again)

- src/classes/Listings.ts
- src/classes/MyHandler/MyHandler.ts
Should also resolve unhandled rejection error:
> 🔨 Bypass checking listings if failed, just delete all on shutdown

- src/schemas/pricelist-json/listing-note.ts
Might be useful if you want to make a custom listing note (without any parameters).
If still have parameters, it will automatically be trimmed to 200 characters.
> ↩ Revert listings note character limit to 200

- src/classes/Bot.ts
🚧 A failsafe from this error (crash):
> 🔨 Fix missing catch on `getPartnerDetails`

- src/classes/Commands/sub-classes/Options.ts
- src/classes/Listings.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
New option:
- `details.showAutokeys` (default: `true`).
Set this to `false` if you don't want the bot to add "[𝐀𝐮𝐭𝐨𝐤𝐞𝐲𝐬] " in front of the listing note if it's managed by the Autokeys feature.
> ✨ Add toggle option to show [𝐀𝐮𝐭𝐨𝐤𝐞𝐲𝐬]

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Help.ts
- src/classes/Commands/sub-classes/Status.ts
- src/lib/tools/polldata.ts
wipestats: wipe trade statistics via command
You can now use !wipestats to wipe the statistics returned by 
the !stats command, as opposed to having to stop the bot and
manually delete the polldata.json file.
Refs: https://discord.com/channels/664971400678998016/666909760666468377/1036824922430898186
> ✨Add way to wipe trade statistics while the bot is on

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Help.ts
- src/classes/Commands/sub-classes/PricelistManager.ts
This command was requested a couple of times, so I decided to implement it.
How to use: as an admin, send `!groups` to get a list of groups in your bot's pricelist.
> ➕ Add `!groups` command

- src/classes/DiscordBot.ts
Yet another bunch of fixes related to the Discord interface.
- Fixed crash when Discord bot tries to start, but fails
- Improved validation of admins' ids (to disallow having different steam ids with the same non-null discord id)
Maybe something else will be added, but idk ¯\\\_(ツ)_/¯
> More Discord fixes

- src/classes/Commands/sub-classes/Status.ts
A little addition to the #1405.
> 🔨 Make sure to also reset the `statistics` options when using the `!wipestats` command

- src/classes/DiscordBot.ts
Currently available: `/uptime`
> 🧪 add experimental slash command for Discord UI

- src/classes/MyHandler/offer/accepted/updateListings.ts
- src/lib/DiscordWebhook/sendAlert.ts
> 🔨Temporarily disable item with ppu if failed to update

- .example/options.json
- src/classes/Inventory.ts
- src/classes/Options.ts
- src/lib/data.ts
- src/schemas/options-json/options.ts
Per the [March 30th patch](https://wiki.teamfortress.com/wiki/March_30,_2023_Patch) the inventory now returns Voices from Below
Also added DeprecatedJsonOptions to allow migration of options in predicable way.
This fixes starting you bot and getting the following error because Voices From Below returns an "undefined" key with no high value type.
>  {"level":"error","message":"TF2Autobot failed to start properly, this is most likely a temporary error. See the log:\r\npackage.version: 5.6.0; node: v16.13.2 win32 x64}\r\nStack trace:\r\nTypeError: Cannot read properties of undefined (reading 'replace')\n    at c:\\tf2autobot\\dist\\classes\\Listings.js:463:61\n    at Array.forEach (<anonymous>)\n    at Listings.getDetails (c:\\tf2autobot\\dist\\classes\\Listings.js:431:37)\n    at …
> fix: 🐛 "Voices From Below" renamed to "Voices from Below"

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Help.ts
On-demand command. Use this command to withdraw all items from your bot.
Optional Parameters:
- `max`: default is Infinity. If the amount of item x in your bot inventory > max, then the bot will only add item x to withdraw until max amount you set.
- `withgroup`: no default value. Use this if you want to withdraw only a certain group in your pricelist.
> ✨ add `!withdrawAll` command

- src/classes/Inventory.ts
Not sure why the bot sometimes still uses the old name instead of the new one, so this should replace the "F" to "f", and prevent it from being undefined.
Thanks @joekiller for the report.
> 🐛 fix undefined "Voices from Below" spell

- package-lock.json
- package.json
- src/app.ts
- src/classes/Bot.ts
- src/classes/BotManager.ts
- src/classes/Listings.ts
- src/lib/bans.ts
- src/lib/helpers.ts
This works around the bot getting into an infinite loop/flaming startup death if the bp mass delete listing endpoint isn't working.
It patches in the currently deleted ListingManager.removeListings function. Once [this pr to add removeListings back](https://github.com/TF2Autobot/node-bptf-listings/pull/9) is accepted, the patching can be removed and just the call can be used.
> Use alternative delete if needed

- src/classes/Bot.ts
This simple and innocent-looking change is what causes the `!halt` and `!unhalt` commands to break.
> Fix broken halt command

- src/classes/Commands/sub-classes/Manager.ts
Instead of executing `pm2 restart ecosystem.json`, we use the already available method to restart the bot, becasue people might not run the bot with PM2 using the ecosystem.json file (maybe with `.env`), or their ecosystem.json file named differently (such as `.ecosystem.json` - idk why they do things like this), etc.
> Fix `!updaterepo` command

- package-lock.json
- package.json
Apparently, the latest version of `ws` (or any version 8) still crashes the bot whenever the connection to prices.tf websocket failed. Downgrading to the latest version 7 should help solve this problem.
> Downgrade `ws` package

- src/classes/Options.ts
- src/classes/Pricelist.ts
- src/schemas/options-json/options.ts
Use case:
- High-frequency custom pricer might need to set the `rewriteFile.count` option to 100 or more.
- Bot with a lot of items in the pricelist (with `autoprice` set to `true`) that is experiencing slow performance: can try another value other than the default (1).
Reference:
- https://github.com/Hhanuska/tf2autobot/commit/54c408936cc923d56d525f01726c042a84e1ec75
> An option to limit pricelist rewrite

- src/classes/Carts/UserCart.ts
- src/classes/Inventory.ts
fixes commands like !sell (generic unusual).
add findByPartialSku() for Inventory.ts which is called when an unusual object has no effect. Is called when searching for generic unusuals in other player's inventory.
fixes: https://github.com/TF2Autobot/tf2autobot/issues/1682
> fix sell commands not working for generic unusuals

- src/classes/Commands/functions/utils.ts
- src/classes/__tests__/Commands/functions/utils.ts
Fixed invalid handling one word item names (e.g. `Maul`) on `!buy` or `!sell`. As of now, it parses the item name from `!buy 5 Maul` as `5 Maul` instead of `Maul`.
Basically, the change is:
```typescript
if (... && args.length > 2) { ... }
```
to
```typescript
if (... && args.length > 1) { ... }
```
, but for testing purposes parsing logic moved to a separate function `parseItemAndAmountFromMessage`.
Apparently, the function `getItemAndAmount(...)` used to accept message with command included, but now all references use it as follows:
`getItemAndAmount(steamID, CommandParser.removeCommand(message), this.bot, prefix);`
, so the command is not included anymore.
The syntax below used instead of unpacking to make linter happy:
```typescript
const name = parsedMessage.name;
let amount = …
```
> Fixed handling one word item name on buy/sell

- package-lock.json
- package.json
- src/classes/Bot.ts
- src/classes/BotManager.ts
- src/classes/Handler.ts
- src/classes/MyHandler/MyHandler.ts
- src/resources/paths.ts
Redo methods to log in to Steam.
Reference:
https://github.com/tf2-automatic/tf2-automatic/pull/334/files by @Nicklason
> Redo logging in

- src/classes/Commands/Commands.ts
- src/classes/Commands/sub-classes/Crafting.ts
- src/classes/Commands/sub-classes/Help.ts
Old:
- `!craftToken slot melee 10`
- `!craftToken class soldier max`
Now:
- `!craftToken melee 10`
- `!ct soldier max`
> 🎯 Simplify craftToken command

- src/classes/Bot.ts
When logging in the bot removes error listeners and only adds them back when successfully logged in. This means that if you first start the bot and get the accessdenied error, then the bot will keep crashing because it keeps trying to sign in using the invalid refresh token.
Bot registers handler for error events on the client:
https://github.com/TF2Autobot/tf2autobot/blob/133b3da1d3e96a66fe93c2d698d3d1d02ccf5bea/src/classes/Bot.ts#L846
https://github.com/TF2Autobot/tf2autobot/blob/133b3da1d3e96a66fe93c2d698d3d1d02ccf5bea/src/classes/Bot.ts#L1616-L1644
Bot removes error listeners when attempting to log in:
https://github.com/TF2Autobot/tf2autobot/blob/133b3da1d3e96a66fe93c2d698d3d1d02ccf5bea/src/classes/Bot.ts#L1389-L1397
Bot does not handle access denied errors in the login error …
> fix: remove refresh token on access denied

- package-lock.json
- package.json
- src/app.ts
- src/classes/Autokeys/Autokeys.ts
- src/classes/Bot.ts
- src/classes/Carts/Cart.ts
- src/classes/Carts/CartQueue.ts
- src/classes/Commands/Commands.ts
- src/classes/DiscordBot.ts
- src/classes/DiscordWebhook/utils.ts
- src/classes/Friends.ts
- src/classes/InventoryApis/InventoryApi.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/TF2Inventory.ts
- src/classes/Trades.ts
- src/lib/apiRequest.ts
- src/lib/bans.ts
- src/lib/pricer/custom/custom-pricer-api.ts
- src/lib/pricer/pricestf/prices-tf-api.ts
- src/types/common.d.ts
- 🔄️ Some refactoring on the codes
- 🔕 Stop sending pre-accepted messages to non-friends (061931e)
- 🔨 Fix duplicate message in the `!help` command ([#1752](https://github.com/TF2Autobot/tf2autobot/pull/1752)) - @Nevskjij
- 🔨 Fix bot not deleting the "refresh token" on Access Denied error ([#1776](https://github.com/TF2Autobot/tf2autobot/pull/1776)) - @Nicklason
- 🔨 Fix `!sku` command due to an empty effect name (https://github.com/TF2Autobot/node-tf2-schema/commit/30e7ba4ec5379b838ac89c0fa682fb7ee9d76a11)
> Prepare v5.13.0

- .dockerignore
- Dockerfile
Fixes an issue where the latest version of typescript cannot compile TF2Autobot by removing the package-lock.json from the .dockerignore so it is included in the build process.
> Include package-lock.json in Docker build

- src/classes/DiscordWebhook/sendTradeDeclined.ts
- src/classes/MyHandler/MyHandler.ts
- src/classes/MyHandler/offer/notify/declined.ts
- src/classes/Options.ts
- src/schemas/options-json/options.ts
Adds an option for controlling whether or not a trade offer will be accepted / processed if both our and their side of a trade offer contain items other refined metal and keys.
Setting: miscSettings.itemsOnBothSides
Also fixes a typo in the sendTradeDeclined preventing the webhook from properly displaying the bot's avatar if not manually set in the options.
🫡
> Add an option for denying trades with items on both sides of the trade.

- src/classes/DiscordBot.ts
Solves [issue #1794](https://github.com/TF2Autobot/tf2autobot/issues/1794).
My instance threw this error on start:
```
[Timestamp] info: Signed in to Steam!
[Timestamp] info: Initializing Discord bot...
[Timestamp] debug: New web session
[Timestamp] warn: Failed to start Discord bot:  Cannot read properties of undefined (reading 'toString') {}
TypeError: Cannot read properties of undefined (reading 'toString')
at DiscordBot.start (tf2autobot/dist/classes/DiscordBot.js:48:28)
at async tf2autobot/dist/classes/Bot.js:633:29
[Timestamp] error: TF2Autobot failed to start properly, this is most likely a temporary error. See the log:
package.version: 5.13.2; node: v23.9.0 linux x64}
Stack trace:
TypeError: Cannot read properties of undefined (reading 'toString')
at DiscordBot.start …
```
> Fix Discord rate limit error loop
