TF2Autobot/tf2autobot

src/classes/DiscordWebhook.ts, src/classes/MyHandler.ts
Mention on accepted INVALID_ITEMS overpay:
- fix bot mention if a trade on the trade partner side contains any craftweapons (5e13b5a)
- add our side check (62274c0)
- more strict check before mentioning (59de6de)
- change reset location (b6a31f8)
=> minor update: fix

src/classes/Commands.ts, src/classes/Listings.ts
- fix `!relist` command to actually do relist (which remove, check and add to backpack.tf) (f9ed24b)
=> fix v1.2.11 don't actually do relist, now it will.

README.md, src/classes/DiscordWebhook.ts, src/classes/MyHandler.ts
- add missing boolean operator
- fix steam chat offer/trade summary
- fix undefined string on offer review with Discord Webhook
=> minor fixes

src/classes/MyHandler.ts, src/classes/TF2GC.ts
- fix duplicated weapons don't get crafted
=> fix weapon crafting problem

src/classes/Commands.ts
improve the bot command descriptions and some other various bot responses.
=> improve bot responses

src/classes/MyHandler.ts, src/classes/TF2GC.ts
=> Craft class weapons

package-lock.json, package.json, src/app.ts, src/classes/CartQueue.ts, src/classes/Commands.ts, src/classes/MyHandler.ts
I've gone through the TF2Autobot project and attempted to correct any spelling or grammatical errors that exist in messages and logging. Hopefully this helps make some of the messages that the bot sends more clear to users and owners. If there are any questions or changes that should be made, please feel free to leave a comment.
**Note:** This PR also includes a fix that reverts some logic introduced in 6e5350b624e6f5485539ff4272752410269ca560. The aforementioned commit makes it so that the bot sends both the default success message _and_ the owner's custom success message. This has been corrected to include either the default success message _or_ the custom success message (if it exists). These specific changes can be viewed in 39a5d161dc3b354a62964d251434a8ee267f6ce5.
(As this is my …
=> Grammar Corrections & CUSTOM_SUCCESS_MESSAGE Refactor

src/classes/MyHandler.ts
=> v1.6.6.1 - Urgent fix

src/classes/Commands.ts, src/classes/Listings.ts, src/classes/Pricelist.ts, src/schemas/pricelist-add.ts, src/schemas/pricelist.ts
- `notebuy` and `notesell` on `!add` or `!update` commands.
=> add custom listing note parameters

src/classes/Commands.ts, src/classes/UserCart.ts
- fix bot crash when manually accepting trades
=> v1.7.0.1 - patch

src/classes/Pricelist.ts
- fix pricelist webhook not updating
=> v1.7.0.3 patch

src/classes/Autokeys.ts, src/classes/Commands.ts, src/classes/Pricelist.ts
- Fix scrap adjustment affect the global key rate
=> Fix scrap adjustment affect the global key rate

src/classes/MyHandler.ts
- fix uptime showing 50825 years.
=> v1.7.1.1 - patch - fix uptime 50825 years.

src/classes/DiscordWebhook.ts
- replace `#` with the `@` symbol (47a21e8).
=> v1.7.3.2 - patch

src/classes/DiscordWebhook.ts
=> v1.7.3.3 - remove logging

.github/FUNDING.yml
=> non-version merge

package-lock.json, package.json
- fix items with "Kit" (such as Killer's Kit, Coffin Kit, and Summer Starter Kit) listed as Killstreak Kit on backpack.tf
=> v1.7.3.4 - update bptf-listing-2 module

.github/FUNDING.yml, src/classes/MyHandler.ts
- fix misplaced sheens/killstreakers
=> v1.7.3.5 - patch/fix

src/classes/MyHandler.ts
- fix accepted `INVALID_ITEMS` did not automatically been added to the pricelist if a trade contains `HIGH_VALUE` items.
=> 1.7.3.6 - patch

src/classes/Commands/main.ts
Example output from these changes:
These changes address enhancements described in #162
=> Add confirmation to !delete command

src/classes/Commands.ts
- fix `accept` and `decline` commands
=> v1.7.3.7 - patch

src/classes/MyHandler.ts
- fix high value does not show in offer review
=> v1.7.3.8 - patch

package-lock.json, package.json, src/classes/Bot.ts, src/classes/BotManager.ts, src/classes/Friends.ts, src/classes/MyHandler/MyHandler.ts, src/types/modules/steam-user/index.d.ts
Add more thorough types for steam-client.
This will help with the mock interface down the line.
TradeManager still needs this treatment but that'll have to be later.
=> V2 type updates

package-lock.json, package.json, src/classes/CommandParser.ts, src/classes/Commands/optionsCommands.ts, src/classes/__tests__/CommandParser.ts
This should simplify handing of arrays for the parser. Fixing #180
=> parse arrays in CommandParser with tests

src/classes/Carts/CartQueue.ts, src/classes/Carts/UserCart.ts, src/classes/Commands/Commands.ts, src/classes/Commands/optionsCommands.ts, src/classes/MyHandler/MyHandler.ts, src/classes/Options.ts, src/lib/validator.ts, src/schemas/options-json/export.ts, src/schemas/options-json/options.ts, src/schemas/options-json/weapons-as-currency/weapons-as-currency.ts
I don't feel like testing so feel free to test this. Thank you.
=> #127 option to exclude uncraft weapons as currency

src/classes/Commands/Commands.ts
What a headache for such a simple fix... 😒
=> Fix crash in !price command

src/classes/Autokeys/Autokeys.ts, src/classes/Commands/optionsCommands.ts, src/classes/MyHandler/MyHandler.ts
=> let !config trigger autokeys updates

src/classes/Options.ts, src/classes/__tests__/Options.ts
This should eliminate the possibility of options.json getting overwritten with defaults if it is malformed.
=> fix nuking of options.json if file is malformed

package-lock.json, package.json, src/classes/Options.ts, src/classes/__tests__/Options.ts, src/types/modules/jsonlint/index.d.ts
This adds informative linting to all JSON files in the path `files\<steamAccountName>\*.json`.
=> jsonlint all the files

src/classes/Listings/Listings.ts
bind(this) always returns a new function reference which is why it wouldn't unbind
https://stackoverflow.com/a/22870717/2240967
=> fix runaway check function

src/classes/Trades.ts
Attempt to confirm offers more then once.
=> Make recursive and clean up trades.ts

src/app.ts, src/classes/Bot.ts, src/classes/BotManager.ts, src/classes/MyHandler/SocketManager.ts, src/classes/Pricelist.ts
This moves socket operations out of constructors into a manager.
Also cleaned up patching so that behavior of Manager is consistent when constructed.
=> Encapsulate socket operations

src/classes/Bot.ts, src/classes/Carts/Cart.ts, src/classes/Commands/Commands.ts, src/classes/Friends.ts, src/classes/Listings/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/accepted/updateListings.ts, src/classes/Pricelist.ts, src/classes/TF2Inventory.ts, src/lib/bans.ts, src/lib/ptf-api.ts, src/types/modules/request-retry-dayjs/index.d.ts
- tighten prices.tf interface
- fix optimistic type conversions
=> ensure getPricesTF returns a price parsed with Currency()

src/classes/MyHandler/MyHandler.ts, src/classes/Trades.ts
=> Async on offer action

src/classes/Commands/Commands.ts
this is just a hotfix for this one bug
=> 🐛 fix sellCart not counting their items

src/classes/Bot.ts, src/classes/Carts/AdminCart.ts, src/classes/Carts/Cart.ts, src/classes/Carts/UserCart.ts, src/classes/Commands/Commands.ts, src/classes/Commands/functions/utils.ts, src/classes/Inventory.ts, src/classes/InventoryManager.ts, src/classes/Listings/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/SocketManager.ts, src/classes/Pricelist.ts, src/types/common.d.ts
Allow bot to buy generic unusual orders.
Fixes #230
=> Accept generic unusual trades

src/classes/Inventory.ts, src/classes/Listings/Listings.ts
- want to also test the latest commit
=> merge development with debug-overstocked branch

src/classes/Bot.ts, src/classes/Carts/AdminCart.ts, src/classes/Carts/UserCart.ts, src/classes/Commands/functions/misc.ts, src/classes/Commands/functions/pricelistManager.ts, src/classes/Commands/functions/review.ts, src/classes/Commands/functions/status.ts, src/classes/Inventory.ts, src/classes/Listings/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/accepted/processAccepted.ts, src/classes/MyHandler/offer/review/send-review.ts, src/classes/Trades.ts, src/lib/DiscordWebhook/sendOfferReview.ts, src/lib/tools/check.ts
combine high value and Dueling Mini-Game/Noise Maker uses in Inventory Dictionary, this way we don't load `EconItem[]` in memory.
=> 🧬 refactor Inventory, ⚡ better performance

src/classes/Autokeys/Autokeys.ts
- 🐛 fix Autokeys not able to sell when banking
=> patch - v2.3.8

src/classes/__tests__/Options.ts, src/lib/__tests__/validator.ts, src/schemas/options-json/options.ts
currently failing due to permissive validation 🐛
once these tests pass then the bug is fixed.
=> ✅ add removeCliOptions and schema validation tests

.gitignore, src/classes/Listings.ts
- 🐛 fix bot crash if `details.highValue.showStrangeParts` is set to `true`
=> 🐛 fix bot crash if `showStrangeParts` is set to `true`

src/classes/Bot.ts, src/classes/Commands/Commands.ts, src/classes/Commands/functions/manager.ts, src/classes/Commands/functions/status.ts, template.ecosystem.json, template.env
- 🐛 fix false error on `!updaterepo` command
- 🔨 make `!clearfriends` an `async` function with 2 seconds interval between each message to send to the friends to be removed (prevent Steam from detecting the bot as spamming thus make it unable to send any more messages).
- 🔨 use user-customized option (`customMessage.clearFriends`) if not empty on `!clearfriends` command.
- 🎨 improve some wordings in `!version` and `!updaterepo` commands.
- 🔔 add `"version"` as `ALERTS` element (send alert to ADMINS if a new version has been released).
=> v3.0.3 - minor fixes

src/classes/Carts/AdminCart.ts, src/classes/Carts/DonateCart.ts, src/classes/Carts/PremiumCart.ts, src/classes/Carts/UserCart.ts
- 🐛 fix wrong altered amount on `!buy`/`!sell` commands.
=> v3.0.4 - important patch

src/classes/Commands/functions/review.ts, src/classes/Listings.ts
- 🐛 Autokeys: fix keys got relisted after each successful trade
=> v3.2.1 - patch

package.json, src/classes/Commands/Commands.ts, src/classes/Commands/functions/manager.ts
Recently always got some weird stuff. I wonder if this will work. Please help review.
Thank you.
=> 🔨 improve `!updaterepo` command

src/classes/Autokeys/Autokeys.ts, src/classes/MyHandler/offer/accepted/updateListings.ts
- 🔨 fix backpack.tf listings details for Mann Co. Supply Key (stock or updated price) not getting updated (if you do manual trading, with autokeys disabled)
=> v3.4.2 - small patch

src/classes/BotManager.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/Commands/sub-classes/Misc.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/accepted/processAccepted.ts, src/classes/MyHandler/offer/accepted/updateListings.ts, src/classes/MyHandler/offer/review/reasons/disabledItems.ts, src/classes/MyHandler/offer/review/send-review.ts, src/classes/Pricelist.ts, src/classes/Trades.ts, src/classes/__tests__/Pricelist.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/sendOfferReview.ts, src/lib/DiscordWebhook/sendTradeSummary.ts
- 🔄 replace bracket with just a dash to not confuse the generated URL (Steam Chat, on an error to accept an offer)
- 🔨 fix the wrong position (pure and inventory in Offer review - Discord Webhook)
- 🤝 custom-pricer friendly (#363)
=> fix typo, etc

.github/workflows/docker-commit.yml, .github/workflows/docker-latest-tag.yml, .github/workflows/docker-release.tag.yml, Dockerfile
This PR containerizes the application into a Node.js image for the given tag/commit/latest (for master). The idea behind it is to be able to run it in Docker without issues and orchestrate multiple apps without having to deal with actual servers.
Currently, the PR creates Docker tags for a release, a commit and for the latest master branch. If only releases might suit, I can update the PR to include only the releases. However, it is recommended to keep a history for the GIT SHA tags in order to be able to debug a specific commit in Docker (in case it is needed).
The builds are made for the following Node.js versions:
- `15.10-alpine`
- `15.10-buster`
- `15.10-buster-slim`
- `15.10-stretch`
- `15.10-stretch-slim`
- `lts-alpine`
The tag formats are:
- for commits: `[git_sha]-[node_version]` …
=> [development] Docker Build

src/classes/MyHandler/MyHandler.ts
=> Ensure generic match is used against 'their' inventory

src/classes/Carts/Cart.ts, src/classes/Commands/Commands.ts
=> 🔨 improve `!deposit` command and perform items lookup

src/classes/Commands/functions/utils.ts
- at the same time, fix the bot crashed if the user inputs the quality parameter as a number.
=> 🔄 more flexibility when adding items with params

src/classes/Autokeys/Autokeys.ts
=> 🔨 fix failed to disable Autokeys error

src/classes/Carts/CartQueue.ts, src/classes/Trades.ts, src/lib/DiscordWebhook/sendAlert.ts
=> 🔨🎨 fix duplicate uptime message

src/classes/Commands/sub-classes/PricelistManager.ts
=> 🔨 small refactor on `!autoadd` cmd

src/classes/Autokeys/Autokeys.ts, src/classes/Bot.ts, src/classes/BotManager.ts, src/classes/Carts/CartQueue.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/Commands/sub-classes/Message.ts, src/classes/Commands/sub-classes/Misc.ts, src/classes/Commands/sub-classes/Options.ts, src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Commands/sub-classes/Request.ts, src/classes/Commands/sub-classes/Review.ts, src/classes/Commands/sub-classes/Status.ts, src/classes/Friends.ts, src/classes/Groups.ts, src/classes/Handler.ts, src/classes/Inventory.ts, src/classes/InventoryManager.ts, src/classes/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/Pricelist.ts, src/classes/TF2GC.ts, src/classes/TF2Inventory.ts, src/classes/Trades.ts
=> 🔨🎨 refactor class properties and constructor

src/classes/Pricelist.ts
=> 💅 include name in partial price update summary

src/classes/Bot.ts
Cleaned up Bot.ts
There still is ESLINT error on L336, which could be fixed by making `onPricelist` synchronous.
=> Refactor Bot.ts

src/classes/Options.ts, src/lib/DiscordWebhook/sendOfferReview.ts, src/lib/DiscordWebhook/sendTradeSummary.ts, src/lib/tools/summarizeItems.ts, src/lib/tools/summarizeOffer.ts, src/schemas/options-json/options.ts
Useful if you have a spreadsheet that refers to prices.tf/custom-autopricer item name (which shown in proper and full item name)
=> ✨option to show proper name (with "The", no short)

src/classes/Pricelist.ts
Verify keyPrices from the source (prices.tf or custom-pricer) with the below condition:
https://github.com/TF2Autobot/tf2autobot/blob/5ce5b7dc1d93c1cae38da2577d4b1146ee8525f2/src/classes/Pricelist.ts#L568-L570
=> keyPrices verification and refactor Pricelist.ts

src/classes/Bot.ts
- 🔨 fix failed to start on Linux (idk why)
Running fine on Windows. 🤷‍♀️
=> v3.6.1 - patch

src/lib/tools/summarizeOffer.ts
Review:
Also can occur in logs/steam chat.
=> Fix stock changes 2

src/classes/Pricelist.ts
=> 🔨 fix partial price update feature

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/PricelistManager.ts
- ✨🎨 show listings used/cap on `!add` & `!update` cmd
- ✨ add `!getSlots` command
=> 🎨 Show current listings slots used per cap

src/lib/DiscordWebhook/pricelistUpdate.ts
=> 🔨🎨 fix standard tf2 currency float value

package.json, src/classes/Bot.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/Commands/sub-classes/Status.ts
- inform the bot owner whether it's a good time to use `!updaterepo` command to update or not.
=> ✨ add "updateMessage" in package.json

src/classes/Commands/sub-classes/PricelistManager.ts
- 🔄 fix steam chat limit - decrease 200 to 50
=> small patch on `!getAll` and `find` commands

package.json, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Manager.ts
- 🔄 refactor `!updaterepo` command - no confirmation needed
=> refactor !updaterepo command

src/classes/MyHandler/offer/accepted/updateListings.ts
- latest changes only ignore pure, thus makes the bot treat weapons as an invalid item and add them to the pricelist to sell even if you have weaponsAsCurrency enabled.
- this will fix the issue.
=> 🐛 fix weapons not being ignored

src/lib/tools/summarizeOffer.ts
- in offer review and logs - now our side (third time)
=> 🐛 fix wrong amount in stock changes

src/classes/Trades.ts
=> 🔄 use log instead of save in polldata

src/classes/Pricelist.ts
=> ⛔ do not update price if group is `isPartialPriced`

src/classes/InventoryManager.ts
Only use generic counts if we have a generic sku in the first place.
fixes #457
=> Fix generic without generic

src/classes/MyHandler/offer/accepted/updateListings.ts
=> 🐛 fix wrong selling price - autoAddPainted

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Request.ts, src/classes/MyHandler/MyHandler.ts
- always run `priceheckAll` in the background (15 minutes delay between each execution).
- since this will always run in the background, `!pricecheckall` command is now removed to prevent conflict (or rate limit).
=> ✨ background pricecheckAll, 🔥 remove `!pricecheckall`

src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Pricelist.ts, src/lib/DiscordWebhook/export.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/pricelistUpdateFailed.ts
=> 🚧 add a failsafe in `handlePriceChange` method

src/classes/MyHandler/MyHandler.ts
Discord: https://discord.com/channels/664971400678998016/666909760666468377/821163786403577866
=> 🔨 revert changes, fix overstocked weapons

package-lock.json, package.json
Fixes #474
Wrong:
Correct:
`bptf-listings-2` changes: https://github.com/TF2Autobot/node-bptf-listings-2/commit/668d4f1d7957a4be5556dced40cc8f93b3b3b232
=> 🔄 update `bptf-listings-2`, 🔨 fix buy order for Killstreak Kit

src/classes/Options.ts, src/classes/Pricelist.ts, src/schemas/options-json/options.ts
- This is especially for those that use custom pricer. Default is true.
=> ✨ add an option to toggle show failed price update

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts
=> ✨ add `!sku` command

src/classes/MyHandler/offer/accepted/updateListings.ts, src/lib/DiscordWebhook/sendAlert.ts
=> Fix wrong info on auto-update partially priced item

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts
- 🎭 `!getSlots` or `!listings` command
=> different commands, same function

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Request.ts
Prevent "Temporary IP banned" issue.
=> ✨ implement queue on `!pricecheckall` command

src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/pricelistUpdateFailed.ts
This is especially for aggressive autopricer, but I wonder if 100 ms is enough.
=> ✨ Price update (Discord Webhook): implement queue

src/classes/Pricelist.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/pricelistUpdateFailed.ts
- reposition sending the update to Discord webhook.
- refactor on the queue classes.
=> 🔨 Price update: fix some not sent

src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Commands/sub-classes/Request.ts
because
https://github.com/TF2Autobot/tf2autobot/blob/f0cee7a938941f58a006fc80e9671eb81f04b289/src/classes/Commands/sub-classes/PricelistManager.ts#L910
=> 🔨 Pricecheck: fix pricecheck on commands

src/lib/tools/summarizeOffer.ts
yes again, hopefully, the last.
=> 🔨 fix wrong stock changes (again)

src/classes/BotManager.ts, src/classes/MyHandler/SocketManager.ts
=> 🤝 connect to socket after the bot starts

src/lib/tools/summarizeItems.ts
=> 🔨 fix wrong info

src/classes/Commands/sub-classes/PricelistManager.ts
You can now use `item` parameter in `!add` command.
=> ✨ add an ability to add item with an item full name

src/classes/Commands/sub-classes/PricelistManager.ts
=> 🔨 fix unable to add an item with `item` parameter

src/classes/Carts/UserCart.ts
=> 🎨 escrow message when using command

src/lib/extend/item/getSKU.ts
- the sku generated was the sku without any painted partial sku.
=> 🐛 fix not detect Legacy Paint item in inventory

src/lib/extend/item/getSKU.ts
=> 🐛 fix not detect legacy painted item in inventory

src/classes/Pricelist.ts
currently no info about the item:
=> 🔨 ppu: fix missing info on reset

src/lib/DiscordWebhook/sendOfferReview.ts, src/lib/DiscordWebhook/sendTradeSummary.ts
=> 🔨🎨 remove discord webhook formatting on fail

src/classes/Commands/sub-classes/Options.ts
=> 🐛 fix Steam chat auto link protocol

.github/workflows/docker-release.tag.yml
Reverts TF2Autobot/tf2autobot#604
=> Revert "Bump crazy-max/ghaction-docker-meta from v2.3.0 to v2.4.0"

package-lock.json, package.json, src/classes/Bot.ts, src/classes/Handler.ts, src/classes/MyHandler/MyHandler.ts, src/types/modules/bptf-listings-2/index.d.ts
Replace deprecated Heartbeat (https://backpack.tf/api/index.html#/auxiliary/App\Controllers\API\User\Auxiliary::heartbeat) with User-Agent (https://backpack.tf/api/index.html#/agent/App\Controllers\API\User\UserAgentAPI::pulse)
=> 🔄 replace deprecated `heartbeat` with `user-agent`

src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/processDeclined.ts, src/lib/DiscordWebhook/sendTradeDeclined.ts, src/lib/tools/time.ts
=> Cleaning declined summary

src/classes/Autokeys/Autokeys.ts, src/classes/Commands/sub-classes/Options.ts, src/classes/MyHandler/MyHandler.ts
- 🔨 ensure keys always get disabled on shutdown
- possible fix for: https://prnt.sc/12sk526
=> Autokeys - possible fixes

src/classes/Inventory.ts, src/classes/TF2GC.ts, src/classes/Trades.ts
=> 🐛 fix unable to continuously delete the same item

.github/workflows/docker-commit.yml, .github/workflows/docker-latest-tag.yml, .github/workflows/docker-release.tag.yml
supersed #642, #643, #644, #645, #646
=> Upgrade/Update GitHub Docker

src/classes/Bot.ts
Should be added on #469 and/or #568, but whatever.
=> 🐛 fix bot crash if no pricelist present

src/classes/Commands/functions/utils.ts, src/classes/Listings.ts
=> 💱 use sku if item name longer than 40 characters

src/classes/Trades.ts
Following the logs, I was provided. 
This is the only promise that I found hanging after the log message `Sending offer...` and before the log message `Sent offer`. 
So I hope this fixes it 😞.
=> Fix queue getting stuck

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Pricelist.ts
- Only `sku` or `item` parameter can be used as the item identifying parameter (`name` and `defindex` - no)
- Separate by a new line.
- Format: !addbulk (sku|item)=\<a\>&[[Listing-parameters](https://github.com/TF2Autobot/tf2autobot/wiki/Listing-settings-parameters)]\<Enter (new line)\>\<second and so on\>...
- Example:
```
!addbulk sku=30186;6
sku=5052;6&max=3
item=A Deep Commitment to Purple&intent=buy
item=Totally Boned Pistol (Minimal Wear)&intent=sell&sell.metal=2&group=skin
sku=5052;6&sell.metal=24&buy.metal=23&max=3
sku=5040;6
sku=31129;6
sku=30753;6
sku=30662;6
sku=5076;6
sku=341;6
sku=30994;6
item=A Well Wrapped Hat
sku=610;6
sku=5871;6;c107&max=10&group=crate
sku=30793;6
sku=5077;6
sku=5038;6
sku=31012;6
sku=6522;6;td-1104
```
=> ✨ add !addbulk command

src/classes/Commands/sub-classes/PricelistManager.ts
=> 💡 skip request pricelist if all items are manually priced

.example/options.json
- `!updatebulk` and `!removebulk` commands - 🔍 add checks if an item exists, 🔨 fix missing `continue` (#709)
=> prepare v4.1.1

src/classes/Commands/sub-classes/Options.ts
=> 🐛 `!clearArray` - fix wrong target

src/classes/Commands/sub-classes/Options.ts, src/classes/Commands/sub-classes/PricelistManager.ts
- 🐛 `!clearArray` command - fix wrong target (#711)
=> prepare v4.1.2

src/lib/extend/item/getSKU.ts
=> 🐛 fix Salvaged Crate not properly detected

src/classes/Bot.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/review/send-review.ts, src/types/modules/steam-user/index.d.ts
~~Untested. I am not sure whether this new method will be able to send messages to non-friends or not.~~ PASSED
Probably fixes:
=> fix bot unable to send review summary through Steam Chat

src/classes/Commands/sub-classes/Options.ts, src/classes/Inventory.ts, src/classes/Options.ts
=> 💡 refactor and possible optimization

src/classes/MyHandler/offer/accepted/updateListings.ts
=> 🐛 fix bot crash on received painted items from admin

package-lock.json, package.json
- Fix problem with the lightning bolt symbol/button on bptf listings sometimes turned into normal trade (⇌)
=> 🔄 reduce interval timer to refresh bptf agent

src/classes/BotManager.ts
=> 🔨 fix shutdown undefined error

src/classes/Commands/sub-classes/Manager.ts, src/classes/MyHandler/MyHandler.ts
I hope this logic is good enough
=> Fix repetitive check

src/classes/Listings.ts
- 🔨 fix repetitive check for missing listings (again) (#750)
- fix useless checks : [image](https://user-images.githubusercontent.com/47635037/123493958-ca053a00-d650-11eb-8d9f-46ce70d7f3d1.png)
=> v4.2.2 - patch

src/classes/MyHandler/MyHandler.ts
- `onBulkUpdatePartialPriced` (on start or restart)
- 🔨🎨 fix broken format: [image](https://user-images.githubusercontent.com/47635037/123495146-09358a00-d655-11eb-89cc-fe873684f55a.png)
- 🔄 only send if less than 20: [image](https://user-images.githubusercontent.com/47635037/123495102-e014f980-d654-11eb-9b8d-376f1815f653.png)
=> patch - 4.2.3

src/app.ts, src/classes/Options.ts, src/lib/DiscordWebhook/sendAlert.ts, src/lib/DiscordWebhook/sendOfferReview.ts, src/lib/DiscordWebhook/sendPartnerMessage.ts, src/lib/DiscordWebhook/sendTradeSummary.ts
=> 🐛 fix `discordWebhook.ownerID` again

src/classes/Inventory.ts, src/classes/TF2GC.ts, src/classes/Trades.ts
Yeah purchased 5 Backpack Expanders (only used 4 because already full 😅) and tested them on Asuna.
(some logs not included in this commit)
=> 🐛 fix timeout problem when using newly bought bp expander

src/classes/Inventory.ts, src/classes/TF2GC.ts, src/classes/Trades.ts
- 🐛 fix timeout problem when using newly bought Backpack Expander (with `!expand` or `!use` commands) (#775)
=> patch - v4.2.7

src/classes/Trades.ts
=> 🐛 fix counterOffer's filter undefined error

src/app.ts, src/classes/Commands/sub-classes/Request.ts, src/classes/Pricelist.ts
- 🔄 only check if `customPricerUrl` is not empty
=> Custom pricer small update

src/classes/Commands/sub-classes/PricelistManager.ts
- patch the `LimitExceeded` problem on `!addbulk`/`!updatebulk`/`removebulk`/`!getAll`/`!find`/`!ppu` commands.
=> ⏳ increase delay between message from 2 to 3 seconds

src/classes/Commands/sub-classes/Status.ts
- 💬 send separate messages if total characters > 4000
=> 🔨 fix rateLimitExceeded on `!itemstats` command

src/classes/Inventory.ts
=> ⛔ do not craft weapons with high value attachments

src/app.ts, src/classes/Options.ts, src/classes/Pricelist.ts, src/classes/__tests__/Options.ts
=> fix false custom-pricer

src/classes/Commands/sub-classes/Request.ts, src/classes/Options.ts, src/classes/Pricelist.ts, src/classes/__tests__/Options.ts
Previous commits causing problems connecting to socket server (prices.tf)
=> Fix xhr problem

src/app.ts
- ~~[ ] priceUpdate thing~~
- ~~[ ] etc~~
=> Dynamic module import implementation

src/classes/Carts/UserCart.ts
On offer received is good:
But then they switch to use chat, and:
😵🥴
=> 🐛 fix able to bypass dupe check

src/classes/Commands/sub-classes/Misc.ts
=> 🔨 fix wrong order

src/classes/Commands/sub-classes/Manager.ts, src/classes/MyHandler/MyHandler.ts
=> 🚮 ignore checking missing listings for disabled items

package-lock.json, package.json, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Manager.ts, src/types/modules/steamcommunity/index.d.ts
=> ✨ `BlockedList` command

src/classes/MyHandler/MyHandler.ts
=> 🐛 fix false disabled item(s)

src/classes/Commands/sub-classes/Crafting.ts
- 🎨 show current stock for each token
- 🐛 fix crafting more than user input amount
=> `craftToken` command: a fix and small improvement

.example/options.json
`!craftToken` command (#834):
- 🎨 show current stock for each token
- 🐛 fix crafting more than user input amount
- 🔨 fix wrong info
=> prepare v4.4.2

src/classes/Commands/sub-classes/Crafting.ts, src/classes/MyHandler/MyHandler.ts
- 🐛 fix an exploit introduced on v4.4.0/v4.4.1 update (#845)
=> URGENT - v4.4.3

.example/options.json, src/classes/Commands/sub-classes/Crafting.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/notify/declined.ts, src/classes/MyHandler/offer/processDeclined.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
- ⛔ always decline an offer containing our side item(s) that has no selling price (#847)
- options.json: 8be0339
=> prepare v4.4.4

src/classes/Trades.ts
For some reason, the `prices[sku]` here can be `undefined`. My only thought is that the bot failed to properly save the offer data.
https://github.com/TF2Autobot/tf2autobot/blob/b960407a1c9d301088c862e34c2dc2c565ba9979/src/classes/Trades.ts#L941-L945
=> 🚧 add a crash failsafe on counteroffer operation

src/classes/Trades.ts
=> 🔨 fix broken counteroffer

package-lock.json, package.json, src/classes/MyHandler/MyHandler.ts
- 🔄 update rate limit (15 req/60 seconds) on creating/removing listings
=> Update bptf listings

src/classes/Listings.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
Maybe preset is better. not sure.
=> ✨ an option to show bold characters

src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/notify/cancelled.ts, src/classes/MyHandler/offer/notify/declined.ts, src/classes/MyHandler/offer/notify/invalid.ts
- this can cause some miscount on the statistics (Declined/Canceled/Traded away)
=> 🔨 fix not save polldata keys if disable notify

src/lib/bans.ts
Because rep.tf complied everything, so should take less time (and also maybe less downtime).
=> ✨🔎 check banned only from rep.tf (others as backup)

src/classes/Bot.ts, src/classes/Options.ts, src/lib/bans.ts, src/schemas/options-json/options.ts
=> ✨🔎 an option to check for Marketplace.tf banned status

src/classes/Bot.ts, src/classes/Carts/Cart.ts, src/classes/MyHandler/MyHandler.ts, src/classes/TF2Inventory.ts, src/lib/bans.ts, src/lib/pricer-api.ts
=> 🔥 remove version on request header

src/classes/Trades.ts
Every time, as far as I am aware.
=> 🐛 fix unable to counter offer with only keys

src/classes/MyHandler/MyHandler.ts
=> 🐛 fix bot not playing game after doing other than accepting an offer

src/classes/Pricelist.ts, src/lib/DiscordWebhook/pricelistUpdate.ts
=> 🔨 Ignore handlePriceChange if no changes in price

src/classes/Commands/sub-classes/Help.ts
Just a simple fix for this issue:
=> fixed help command spacing

src/classes/Commands/sub-classes/Misc.ts, src/classes/Commands/sub-classes/Request.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/accepted/updateListings.ts, src/classes/Pricelist.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/pricelistUpdateFailed.ts, src/lib/tools/summarizeOffer.ts
Since prices.tf website is no longer available.
Example: https://autobot.tf/items/5021;6
Feel free to contribute to the [website repository](https://github.com/TF2Autobot/autobot.tf) (mine is too basic).
=> 🔄 replace prices.tf item page with autobot.tf

src/lib/pricer/pricestf/prices-tf-pricer.ts, src/lib/pricer/pricestf/prices-tf-socket-manager.ts
Changes in the prices.tf side:
=> 🔄 update prices.tf auth through message event

src/classes/Commands/sub-classes/Message.ts
=> 🐛 fix wrong steamID

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Misc.ts
Support optional item sku or item name on `!stock` command
=> ✨ update command: `!stock [sku|item name]`

src/lib/pricer/pricestf/prices-tf-api.ts, src/lib/pricer/pricestf/prices-tf-pricer.ts
=> 🔄 try get pricelist from autobot.tf first

.github/workflows/docker-commit.yml, .github/workflows/docker-latest-tag.yml, .github/workflows/docker-release.tag.yml, package-lock.json, package.json, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Request.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/pricer/pricestf/prices-tf-pricer.ts, src/lib/tools/summarizeOffer.ts
- 🎨 add images for retired keys (Discord Webhook price changes) (f9c765d)
- 🔄 use autobot.tf for effect images (#997)
- 🔄 Docker: when enabled, force it to stop on `!restart` command (#1000) - @rennokki
- ✨ update command: `!stock [sku|item name]` (#1018)
- 🔎 check item existence when adding to pricelist (#1021)
- 🔄 try get pricelist from autobot.tf first (#1022)
- 🔄 Update dependencies
=> prepare v4.6.0

src/classes/MyHandler/MyHandler.ts, src/lib/bans.ts
=> Fix ban check

src/classes/Bot.ts, src/classes/Carts/Cart.ts, src/classes/Friends.ts, src/classes/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/TF2Inventory.ts, src/lib/bans.ts, src/lib/pricer/custom/custom-pricer-api.ts, src/lib/pricer/pricestf/prices-tf-api.ts
- this should fix network socket leaks
Best practice is to always close the connection. When using requests raw method it is noted that .end is not always used.
=> 🐛 fix requests not being ended

src/classes/Commands/sub-classes/Options.ts, src/classes/Listings.ts, src/classes/MyHandler/MyHandler.ts, src/classes/Options.ts, src/schemas/options-json/options.ts, src/schemas/pricelist-json/listing-note.ts
- 🔥 Remove the autobump feature
- ℹ This removal is due to the latest implementation by Backpack.tf which make this feature useless.
- 🔨 Fix Bad Request when creating/updating a listing due to `details` exceeding 200 characters.
- ⚠ The maximum characters allowed in the `details.buy` and `details.sell` in the options.json file have been **reduced to 180 characters**. Please make sure to edit it before restarting/running the bot.
=> prepare v4.8.0

src/app.ts, src/classes/Autokeys/Autokeys.ts, src/classes/Carts/Cart.ts, src/classes/Carts/CartQueue.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/accepted/updateListings.ts, src/classes/Options.ts, src/classes/Pricelist.ts, src/classes/Trades.ts, src/lib/DiscordWebhook/sendAlert.ts, src/schemas/options-json/options.ts
=> ✨ optional separate Discord webhook link for ppu

src/classes/Bot.ts
- 🐛 Fixed empty User-Agent header.
=> prepare v4.9.1

package-lock.json, package.json, src/classes/Options.ts
- [🔄 bump @tf2autobot/bptf-listings](https://github.com/TF2Autobot/tf2autobot/commit/c8fe7191411e624411b2bf1ed675a98247a91a43)
- Only send batch operation limit request every 6 minutes instead of every time before sending batch create/update/delete requests.
- [🔨 fix undefined userAgent header (3)](https://github.com/TF2Autobot/tf2autobot/commit/2efae81cdf9e4b993440210a30d462db90e8d7a7)
- 🔄 downgrade `ws` module
=> prepare v4.9.3

package-lock.json, package.json
- 🔄 bump @tf2autobot/bptf-listings
- 🔨 fix issue with listing details not updated
=> prepare v4.9.4

src/classes/Bot.ts, src/classes/Carts/UserCart.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/notify/declined.ts, src/classes/MyHandler/offer/processDeclined.ts, src/lib/bans.ts, src/types/modules/@tf2autobot/tradeoffer-manager/index.d.ts
Let them clearly know why we don't accept the trade.
=> ✨ show banned results

package-lock.json, package.json, src/classes/Carts/UserCart.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/notify/declined.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
- Check reputation status before accepting any gift. If failed to check, then decline the gift.
- Also check reputation status on receive friend request.
=> Prioritize ban check

src/classes/Commands/Commands.ts, src/classes/MyHandler/MyHandler.ts
- [🔨 Fix Backpack.tf non-premium account does not run the automatic check for missing/mismatching listings](https://github.com/TF2Autobot/tf2autobot/commit/a209564219f6cddcc71cebbcbe103f8bdcc3268c)
- [🔨 Ignore check command spam (in one message) if from admin](https://github.com/TF2Autobot/tf2autobot/pull/1115/commits/8ca5d7187ec25787669867a6ea6edbbc3e26d39b)
- [screenshot](https://user-images.githubusercontent.com/47635037/169947876-a89e5ca5-1f9c-44b6-954a-2dc389768c20.png)
=> prepare v4.11.1

.example/options.json, package-lock.json, package.json, src/classes/Bot.ts, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/MyHandler/MyHandler.ts, src/classes/MyHandler/offer/notify/declined.ts, src/classes/MyHandler/offer/processDeclined.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
Just moving from my fork to the main repository
=> Uploading current version of the feature from my fork

package-lock.json, package.json, src/classes/Listings.ts
=> 🐛 fix creating empty listing

.example/options.json, src/classes/Commands/Commands.ts, src/classes/MyHandler/MyHandler.ts, src/classes/Options.ts, src/lib/pricer/pricestf/prices-tf-api.ts, src/lib/pricer/pricestf/prices-tf-pricer.ts
- [🔄 Change the default value for `reputationCheck` subkeys to `false`](https://github.com/TF2Autobot/tf2autobot/commit/fca33fe44d3534b0289ea51be3c1cb5d1cbc3215)
- [🔄 Set `checkMptfBanned` to default value if MPTF_API_KEY is not set (only for v4.12.1 and below)](https://github.com/TF2Autobot/tf2autobot/pull/1138/commits/e4e645368b0e67ee6165b589b17a7dc5d5cb1549)
- [🔨 Add "Checking" prefix for the message to be ignored](https://github.com/TF2Autobot/tf2autobot/commit/40168bf4dc92171742ed190d6dc926e8240a0cdd) - @RobotoLev
- [🔨 Fix bot failed to retry on `401` (Unauthorized) error due to prices.tf JWT expired](https://github.com/TF2Autobot/tf2autobot/commit/0a36455c8d9391940300ba3f73e61e23fc6233d0) - @RobotoLev
- [🔨 Minor fix on the welcome …
=> prepare v4.13.1

package-lock.json, package.json, src/app.ts, src/lib/DiscordWebhook/utils.ts
=> WIP: Upgrade to axios (continuation)

src/lib/pricer/pricestf/prices-tf-socket-manager.ts
Solves #1137
Reference: https://github.com/websockets/ws#server-broadcast
-->
=> 🐛 fix websocket crash when trying to reconnect

package-lock.json, package.json
=> ⬇ downgrade ws to v7.5.8

src/classes/Commands/sub-classes/Crafting.ts
Using `max` will craft the said token to the maximum amount that the bot can craft.
=> 🔄 update `!craftToken` command, can put `max` as amount

src/classes/Commands/Commands.ts
=> 🐛 fix excessive amount added

src/classes/Commands/Commands.ts
The bot still read the old inventory data, despite already having the items that we want to deposit.
=> 🐛 fix caching admin inventory on `!deposit` command

package-lock.json, package.json, src/classes/Trades.ts
#1120 extension
Crash log:
```
{"level":"debug","message":"Added offer to queue","timestamp":"2022-06-13T03:41:36.817Z"}
{"level":"debug","message":"Only offer in queue, process it","timestamp":"2022-06-13T03:41:36.817Z"}
{"level":"debug","message":"Giving offer to handler","timestamp":"2022-06-13T03:41:36.818Z"}
{"level":"info","message":"Offer #5242273624 from 76561199277354187 is being processed...","timestamp":"2022-06-13T03:41:36.818Z"}
{"level":"warn","message":"Error occurred while handler was processing offer:  Item 11731153573 does not have the \"market_hash_name\" key, unable to correctly identify the item","stack":"Error: Item 11731153573 does not have the \"market_hash_name\" key, unable to correctly identify the item\n    at EconItem.module.exports [as getSKU] …
```
=> 🐛 prevent bot from crashing when there's error processing offer

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Manager.ts
=> 🔨 fix `!clearfriends` not remove blocked friends

package.json, src/classes/Bot.ts, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/Commands/sub-classes/Status.ts
Note that this command will not work when the new version is a major version, which will usually have some breaking changes.
=> ✨ bring back `!updaterepo` command

src/lib/extend/item/getSKU.ts
=> Fix unable to detect Red Rock Roscoe Pistol

package-lock.json, package.json, src/classes/Commands/Commands.ts, src/classes/Commands/functions/utils.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Commands/sub-classes/Request.ts, src/classes/Commands/sub-classes/Status.ts, src/classes/MyHandler/MyHandler.ts, src/classes/Trades.ts, src/lib/DiscordWebhook/sendStats.ts, src/lib/extend/item/getSKU.ts, src/lib/items.ts, src/lib/tools/polldata.ts, src/lib/tools/profit.ts, src/lib/tools/stats.ts, src/resources/paths.ts
- ✨ Rotate polldata (Read: [#1179](https://github.com/TF2Autobot/tf2autobot/pull/1179)) - @Hhanuska
- ♻ Revoke changes made on [#394](https://github.com/TF2Autobot/tf2autobot/pull/394) (Read: [#1184](https://github.com/TF2Autobot/tf2autobot/pull/1184))
- 🔒 Lock `isPartialPriced` parameter ([`7380c8d`](https://github.com/TF2Autobot/tf2autobot/commit/7380c8d8a6ffbb7ef5d961293668cef2a2dc3f51))
- 🔨 Fix unable to detect "Red Rock Roscoe Pistol" ([#1183](https://github.com/TF2Autobot/tf2autobot/pull/1183))
=> prepare v4.16.0

package-lock.json, package.json
I noticed something wrong with my bot when the `Running automatic check for missing/mismatch listings...` did nothing (to create missing listings or to update archived listings).
After some digging, it was because of this:
=> Some fixes on @tf2autobot/bptf-listings

src/classes/Listings.ts
=> 🔨 make sure to convert all name to sku if too long

src/classes/Carts/Cart.ts
Prevent false info on [Error 15](https://steamerrors.com/15)
=> 🔄 properly handle error 15 (not only full backpack)

src/classes/Commands/sub-classes/PricelistManager.ts
=> 🎨 separate active and archived listings

src/lib/extend/item/getSKU.ts
=> 🔨 more refactor, improve performance

src/lib/extend/item/getSKU.ts
Fix #1223
- Accidentally skipped element 0
=> Fix paint not found

package-lock.json, package.json, src/lib/DiscordWebhook/pricelistUpdate.ts
- 🔨 Fix html didn't get filtered on error.
- 🔨 Fix the annoying "filterAxiosError is not a function" error (and probably causing the process to freeze).
=> Prepare v5.0.1

src/lib/bans.ts
=> 🛑 Throw an error on reptf returns invalid response message

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Misc.ts
Links to the bot's Steam, Backpack.tf, and Rep.tf page.
=> ✨ add `!links` command

src/classes/Commands/sub-classes/Misc.ts
=> 🔄 update `!stock` command - include assetids

src/classes/Bot.ts, src/classes/Commands/sub-classes/Manager.ts
=> ✅ Improvement on the `!halt` and `!unhalt` commands

src/classes/Bot.ts
=> 🔨 Fix still check on halt mode

src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/sendAlert.ts
=> 🚧 Discord Webhook alert queue

src/classes/Commands/sub-classes/Options.ts
#1242 extension.
Update Discord presence when updating the `discordChat` options with `!config` command.
=> 🔄 options live update

src/classes/Pricelist.ts
The bot JWT token should have been renewed automatically, but the `try-catch` just caught and throw the error first.
Should resolves:
=> 🔨 retry on error 401

src/app.ts
=> 🔨 Make sure to not include html data

src/classes/Bot.ts, src/classes/BotManager.ts
- Reduce the amount of requests to get user reputation status.
=> 🗃🔎 cache user reputation, reset every 12 hours

src/classes/Bot.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/MyHandler/MyHandler.ts, src/lib/DiscordWebhook/pricelistUpdate.ts, src/lib/DiscordWebhook/sendAlert.ts
- 🔨 Fix unhandled rejection error on failed to get data from Backpack.tf ([0dbc6eb](https://github.com/TF2Autobot/tf2autobot/commit/0dbc6eb37e8d42b62d5efce77c303b2283264d89))
- ↩ Revert changes made in #1247: 
- 🔨 Fix Discord Webhook price update and alert not properly handle rate-limit ([15dcfdc](https://github.com/TF2Autobot/tf2autobot/commit/15dcfdcfe6b7bae8fa90b6412d0375cccaf967f8))
- 🔨 Fix bot not retry getting new loginkey on `InvalidPassword` error ([911c146](https://github.com/TF2Autobot/tf2autobot/pull/1255/commits/911c146e8b3db1be06853a85c65021a10ed570e1))
=> Prepare v5.2.2

src/classes/Trades.ts
=> 🔨 add Active -> Declined to ignore fetch inventory list

src/classes/Commands/sub-classes/Crafting.ts
A restart was the only fix. This should resolve this issue.
=> 🐛 Fix never ending craftToken command when amount is max but have nothing to craft

src/classes/Bot.ts
=> Fix steam-user enums

src/classes/Bot.ts
#1264 extension (yeah tension indeed)
=> 🔨 More problem solving attempt

package-lock.json, package.json
TF2Autobot/bptf-listings@[8038144](https://github.com/TF2Autobot/node-bptf-listings/commit/803814429f7755eed1b9f6b740dc14ac6bfc5377)
=> 🔨 handle Backpack.tf rate limit

package-lock.json, package.json, src/app.ts
Add a little bit more information
=> 1277 extension

package-lock.json, package.json
- 🔄 Bump @tf2autobot/bptf-listings:
- 🐛 Fix not reset isRateLimited property (TF2Autobot/bptf-listings@[c88ee4a](https://github.com/TF2Autobot/node-bptf-listings/commit/c88ee4a9570fcae72088d1df517c371eefd7aa30))
=> Prepare v5.3.1

package-lock.json, package.json
Bump @tf2autobot/bptf-listings:
https://github.com/TF2Autobot/node-bptf-listings/compare/v5.6.6...v5.6.9
=> 🔄 Improvement on handling Backpack.tf rate limit

package-lock.json, package.json
=> 🔄 Bump @tf2autobot/tf2-schema

src/classes/Trades.ts
=> 🐛 Fix broken declined summary

src/classes/DiscordBot.ts
=> Small addition on the Discord bot login log

src/classes/Bot.ts, src/classes/Commands/sub-classes/Misc.ts
=> 🎨 Add a trade offer URL on `!links` command

src/classes/Commands/sub-classes/Review.ts
=> 🔨 Handle characters limit on `!offerinfo` cmd

src/classes/MyHandler/offer/accepted/updateListings.ts
- 🐛 Fix failed to hold high-value items and reset item to autoprice due to this error:
=> Prepare v5.4.1

package-lock.json, package.json, src/classes/DiscordBot.ts
A couple of things related to the Discord module of tf2autobot
=> Discord improvements

src/classes/DiscordBot.ts
Reverts TF2Autobot/tf2autobot#1348
@RobotoLev, looks like there's something that prevents the bot from starting.
I am reverting the changes for now.
=> Revert "Discord improvements"

src/classes/DiscordBot.ts
Reverts TF2Autobot/tf2autobot#1381
@RobotoLev, nvm, I will look into this. Might be Steam's issue too.
=> Revert "Revert "Discord improvements""

src/classes/DiscordBot.ts
Didn't test it (I'm on phone right now), but it should work. 
The problem is: I committed an old code without testing it properly. Or the last commit in #1348 was conflicting with other ones, can't say for sure right now.
=> Fix for #1348

README.md, src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Misc.ts, src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Listings.ts
=> 🐛 Fix `!stock` command showing wrong info

src/classes/DiscordBot.ts
Found out that I used a wrong method to construct `User` object by its id.
I have tested this and it seems to work normally.
=> Another fix for #1348

src/classes/Commands/sub-classes/Status.ts, src/lib/DiscordWebhook/sendStats.ts
=> 🔨 Small fix on #1405

src/classes/Commands/Commands.ts, src/classes/Commands/sub-classes/Help.ts, src/classes/Commands/sub-classes/Options.ts
feature that lets you run a command to backup your pricelist
New feature that allows the user to backup their pricelist.json file easily. It also organizes backups by date.
Refs: https://github.com/TF2Autobot/tf2autobot/issues/1416
=> ✨Add way to backup the pricelist through a command

src/classes/MyHandler/MyHandler.ts
=> 🔨 Do not counter offer if taking our items

src/classes/Bot.ts
A little refactor on the #1447.
=> 🔨 Refactor getting localization file

src/classes/MyHandler/MyHandler.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
- Revert #1455 and add an option to decline instead.
=> Add an option to decline CRIME_ATTEMPT instead of counter the offer

src/classes/Commands/sub-classes/PricelistManager.ts
*Correction on the branch name: `fix-removeall-cmd`
Fix:
=> 🔨 fix wrong logic for withoutgroup on remove all

src/lib/pricer/pricestf/prices-tf-pricer.ts
=> 🔨 Get price from autobot.tf if prices.tf failed

src/classes/Commands/Commands.ts
=> 🔨 Update `!sku` command to support multiple input

src/classes/Bot.ts, src/classes/Options.ts, src/schemas/options-json/options.ts
Pretty simple thing to be sure that your bot won't trade with customers
=> New option to auto-enable halt mode on start

src/classes/Commands/sub-classes/Manager.ts
=> 🔨 Remove extra negative sign on Scrap Adjustment value (!autokeys command)

src/classes/Options.ts, src/lib/bans.ts, src/schemas/options-json/options.ts
The rep.tf site has been blocking the bot from making any request for the past 10 months or more, so I've deemed it unusable and should be removed.
=> 🚮 remove rep.tf from ban checking

src/classes/Bot.ts, src/classes/Handler.ts, src/classes/MyHandler/MyHandler.ts
Improve #1524 to automatically delete the `loginToken` file due to "AccessDenied" error and retry to login again.
=> Update on the new Steam login

src/lib/bans.ts
Should help a bit with blocked region/IP, but it's totally depends on Cloudflare too.
=> Get reputation data from rep.autobot.tf first

package-lock.json, package.json, src/classes/Bot.ts, src/classes/Commands/sub-classes/Manager.ts, src/classes/MyHandler/MyHandler.ts
Possible fix for items not being list on backpack.tf:
- 🚮 Remove some lines that make the bot to give up on trying to list item(s) on backpack.tf (https://github.com/TF2Autobot/node-bptf-listings/commit/c0820298ecd10e9ee804214b316b06a0d57d834e).
- 🚮 Remove auto-check for missing listings feature.
=> Keep retry to list on backpack.tf

package-lock.json, package.json, src/classes/Pricelist.ts
- 🔨 Fix unable to login to Steam due to outdated `steam-user` and `steam-session` packages.
- 🚮 remove check "bptf" as source on handling price change function.
- 🔄️ Bump dependencies
=> Prepare v5.8.3

src/lib/pricer/pricestf/prices-tf-pricer.ts
=> 🔨 Update getPricelist code for prices.tf

package-lock.json, package.json, src/lib/pricer/pricestf/prices-tf-pricer.ts
- 🔨 Remove an unintentional condition that was added by accident (due to copy-pasting from [another source](https://github.com/TF2Autobot/autobot.tf/blob/073eb3d7c8348f71989ac43279179d05e936d151/src/server/lib/pricer/pricestf/prices-tf-pricer.ts#L31-L91)), which prevents the bot from getting the pricelist from autobot.tf. ([5d11ec8](https://github.com/TF2Autobot/tf2autobot/pull/1689/commits/5d11ec81c923229e8a4a46fc7783094902490009))
- 🔨 Fix bot unable to recover if internet connection was lost. ([918d554](https://github.com/TF2Autobot/tf2autobot/pull/1689/commits/918d5545ccadaad156b37ba745384b2179ae769c), [steam-user](https://github.com/DoctorMcKay/node-steam-user/releases))
- 🔄️ Bump dependencies
=> Prepare v5.9.1

src/lib/extend/item/getSKU.ts
=> 🐛 fix craft numbered item not being detected

src/classes/Commands/sub-classes/PricelistManager.ts
This was requested a long time ago but I forgot about it.
Anything else, soon.
=> 🔨 Force intent sell for item added with assetid

package-lock.json, package.json, src/classes/Bot.ts, src/classes/BotManager.ts, src/classes/Commands/sub-classes/PricelistManager.ts, src/classes/Handler.ts, src/classes/MyHandler/MyHandler.ts, src/resources/paths.ts
- 🔄️ Redo log in Steam methods ([#1705](https://github.com/TF2Autobot/tf2autobot/pull/1705), [#1709](https://github.com/TF2Autobot/tf2autobot/pull/1709)) - Credit @Nicklason
- 🔨 Force intent sell for item added with assetid ([#1706](https://github.com/TF2Autobot/tf2autobot/pull/1706))
=> Prepare v5.11.0

src/classes/Carts/UserCart.ts
=> Fixes broken link
